### ISSUE TITLE
Profiles with dependencies

### ISSUE THREAD

**Issue by gjstockham** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#10]
If I have a profile with a dependency, is there any way of it being automatically picked up by AddAutomapper?  I'm currently getting an error about parameterless constructors.

I've tried manually adding it using the cfg => overload of AddAutomapper, but it appears to still try and auto-register the profiles.

Do I have to revert to my own custom setup?

**Comment by jbogard** [comment]
Don't have a Profile with a dependency. Config is static, what is your
dependency?

**Comment by gjstockham** [comment]
Yes, I'm trying to port some older code where the mapper uses an external service, but having re-visited this it can be encapsulated in a resolver, which *can* have a dependency, and solves the problem.

**Comment by jbogard** [comment]
Yep! We have some teams doing the exact same thing. Profiles were loaded up from the container (because it had assembly scanning capabilities), and inevitably dependencies creeped in. Now we moved all those to resolvers.
