### ISSUE TITLE
ServiceCollectionExtensions.AddAutoMapper(IServiceCollection)' is obsolete

### ISSUE THREAD

**Issue by nikoslyk2093** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#105]
Since i updated i am getting this warning now. How do i fix it? 

`Warning	CS0618	'ServiceCollectionExtensions.AddAutoMapper(IServiceCollection)' is obsolete: 'This overload is error prone and it will be removed. Please pass the assemblies to scan explicitly. You can use AppDomain.CurrentDomain.GetAssemblies() if that works for you.'
`

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by nikoslyk2093** [comment]
> I think this is better suited for StackOverflow.

This happened since i updated automapper..

**Comment by lbargaoanu** [comment]
Yes, and that message is telling you what to do about it. If you need further help, SO is the place.

**Comment by willianfalbo** [comment]
Hey @nikoslyk2093 
Try changing your code from:
`services.AddAutoMapper();`
To
`services.AddAutoMapper(typeof(Startup));`
It worked for me!

**Comment by nikoslyk2093** [comment]
I used this and it works. Thanks though ! 
`services.AddAutoMapper(AppDomain.CurrentDomain.GetAssemblies());`
