### ISSUE TITLE
NuGet package reference to ASP.NET Core is misleading

### ISSUE THREAD

**Issue by fernandreu** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#106]
The NuGet package description for `AutoMapper.Extensions.Microsoft.DependencyInjection` currently says:

> AutoMapper extensions for ASP.NET Core

This might be a bit misleading for some users, as it only needs .NET Standard 2.0 to work, with no direct dependency on ASP.NET Core or even .NET Core. In fact, I am using it for a .NET Framework 4.6.1 WPF application that uses Microsoft's dependency injection implementation and it works great.

A more appropriate description might be something like:

> AutoMapper extensions for Microsoft's dependency injection implementation (Microsoft.Extensions.DependencyInjection)

**Comment by lbargaoanu** [comment]
And yet you figured it out :). I think it's much more important to make it obvious to novice users what the purpose of the package is.
