### ISSUE TITLE
Highest available version number is not latest version

### ISSUE THREAD

**Issue by slubowsky** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#108]
Its unfortunate that Version 7.0.0 published on 11/18/18 is not actually the latest version. Latest right now is 6.1.1 published on 6/3/19.
Naive user gets older version installed as Package Manager thinks 7.0.0 is latest.
![image](https://user-images.githubusercontent.com/270589/59636080-a3869d00-9120-11e9-92b7-e1450a77e747.png)

Suggestion - would it perhaps make sense to use same major version as AutoMapper?

**Comment by slubowsky** [comment]
Never mind - that version comes from the MyGet channel. Still unexpected but not a real issue I guess.

**Comment by jbogard** [comment]
No idea here - I thought about keeping the versions the same, but decided
against it, that SemVer was more important.
