### ISSUE TITLE
TDestination doesn't work 6.11

### ISSUE THREAD

**Issue by capdiem** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#110]
![image](https://user-images.githubusercontent.com/16507773/61272183-1d21b180-a7d9-11e9-9376-1ee9538186a6.png)

ReturnType is still `TSource`. But it works when I use `Mapper.Initialize()` instead of `services.AddAutoMapper()` in Startup.cs.

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
