### ISSUE TITLE
AddAutoMapper without parameters is Deprecated but what if the configuration is using AutoMap attribute ?

### ISSUE THREAD

**Issue by Olbrasoft** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#112]

**Comment by lbargaoanu** [comment]
Why is that relevant?

**Comment by Olbrasoft** [comment]
> Why is that relevant?

It is not relevant to delete, Attributes are also loaded only with assemblies that are passed in AddAutomapper (assemblies)
