### ISSUE TITLE
Allow Profile with parameters

### ISSUE THREAD

**Issue by dintecom** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#113]
It would be nice to be able to get Profile dependencies from DI.
https://github.com/AutoMapper/AutoMapper/blob/d5a058e46b3bf27b60af8b268f2ccb63bba14d3d/src/AutoMapper/Configuration/MapperConfigurationExpression.cs#L88
I changed the line above like this:
```csharp
cfg.AddProfile((Profile) ActivatorUtilities.CreateInstance(serviceProvider, type));
```
to do this, I had to copy all the code from AutoMapper.Extensions.Microsoft.DependencyInjection.
I almost managed to solve the problem using `IValueConverter` and `ConvertUsing`, but `ProjectTo` does not work `ConvertUsing<MyValueConverter, string>` and gives an error of `Can't resolve this to Queryable Expression`.

I will give an example:
I am trying to map the Company class to CompanyDto like this:
```csharp
_companyRepository.GetAll().MapTo<CompanyDto>(_mapperConfiguration).ToList()
```
Here such a profile works fine and only the necessary fields are selected from the database:
```csharp
public class CompanyProfile : Profile
{
    public CompanyProfile(UrlService urlService)
    {
        CreateMap<Company, CompanyDto>()
            .ForMember(
                e => e.Url,
                o => o.MapFrom(e => urlService.CompleteDomain(e.Domain)));
    }
}
```
But such a Profile does not work and also forces you to write wrappers on each UrlService function:
```csharp
public class CompanyProfile : Profile
{
    public CompanyProfile()
    {
        CreateMap<Company, CompanyDto>()
            .ForMember(
                e => e.Url,
                o => o.ConvertUsing<DomainUrlConverter, string>(e => e.Domain));
    }
}
```
On version 8, I used a static API, and the configuration was compiled manually, but when migrating to v9 and instance Api, using Profile looks good and I would like to use the original AddAutoMapper extension.

**Comment by dintecom** [comment]
In the example above, `UrlService` has a dependency on `IConfiguration`. I understand what you are talking about, but then there should be another way to use, for example, `IConfiguration` in the mapping settings.

**Comment by jbogard** [comment]
One option would be to register them as Singleton, so that the validation
would prevent you from accessing Scoped objects.

I can see the value of accessing IConfiguration, though.

**Comment by dintecom** [comment]
Yes, that’s exactly what I did before, I had factories for AutoMapper that registered as Singleton and could only receive Singleton dependencies, but not Scoped. But factories are only suitable for post-processing, and ProjectTo is for optimizing queries in DB, and I would like them to use the same IConfigurationProvider.

**Comment by lbargaoanu** [comment]
`ProjectTo` cannot work with DI.
