### ISSUE TITLE
Reigstering AutoMapper in a 3rd party library

### ISSUE THREAD

**Issue by HesamKashefi** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#115]
Hi,
I'm developing a library for asp.net core which has dependency on AutoMapper.
I wanted to use `AddAutoMapper` extension method in my library but I noticed that in it's first line it does this :
  

      // Just return if we've already added AutoMapper to avoid double-registration
      if (services.Any(sd => sd.ServiceType == typeof(IMapper)))
            return services;

Now what should I do?

**Comment by jbogard** [comment]
So your library uses AutoMapper then? `services.AddAutoMapper` registers a single global configuration object, is that what you're expecting? Your mapping profiles to be mixed in with everything else?

**Comment by HesamKashefi** [comment]
Yes, my library uses it but I just use the `ProjectTo` method of it. and I inject `IMapper` into my service to pass configuration to `ProjectTo`.
And I don't have any mappings in my own library that needs to configured.
I expect that `AutoMapper` must be registered either by me or by the user.
So if I don't do it and the user forgets it, my library throws exception for the missing `IMapper`,
the only way that I could think of it was just to tell users to register AutoMapper themselves.

**Comment by jbogard** [comment]
Ah, yeah, I think that’s safest.

**Comment by HesamKashefi** [comment]
OK, thanks.
By the way [here](https://github.com/HesamKashefi/PaginationHelper/blob/master/PaginationHelper/PageHelper.cs) is the code. if anything comes to anyone's mind then ...
