### ISSUE TITLE
Register mappings in a modular architecture

### ISSUE THREAD

**Issue by barthamark** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#116]
I am working on ASP.NET Core web applications using a modular architecture (i.e. contains multiple self-contained reusable projects where each of the projects are modules containing own Startup file, Controllers etc. see: https://github.com/OrchardCMS/OrchardCore ).

Each of my modules contains an own Startup file which where I've registered the mappings using the `services.AddAutoMapper()` extensions before. It worked up until now where I've upgraded to .NET Core 3.0 and also updated the AutoMapper where I've realized that this extension method has been removed (didn't realize that it was obsolete, unfortunately). 

Using the `services.AddAutoMapper(typeof(Startup))` would be great but it turns out that it doesn't work in a modular architecture because once one module registers their own mappings the IMapper interface will be in the service container and the other modules won't be able to register their own mappings. I've checked the code and saw that the obsolete AddAutoMapper actually used all the assemblies and that's why it was working (the other modules still couldn't add another IMapper implementation but I didn't know that this happens in the background because, as mentioned, it was working).

So can you suggest a way to somehow build up a `MapperConfiguration` with all the mappings in each modules and still register one single IMapper instance?

What is important is to keep the modules self-contained and reusable so implementing anything in the main web project is not an option because the modules wouldn't be reusable in other web projects anymore.

**Comment by jbogard** [comment]
This right now isn't possible because `MapperConfiguration` itself isn't modular. The modularity is in the `Profile` classes, not the global configuration.

Is there any technical reason why modules can't just create `Profile` instances, and have them loaded up with `services.AddAutoMapper(allThoseAssemblies);` ?

**Comment by barthamark** [comment]
These projects would be modules for a CMS and needs to be self-contained because if we write an open-source module and make it public to other developers to use it in their CMS instance we don't want them to write any additional code in other projects (e.g. the main web project) just to make it work.

**Comment by jbogard** [comment]
So these are modules in a CMS, and the module uses AutoMapper? How would you deal with conflicting configuration between modules? Configuration is singleton at the moment.
