### ISSUE TITLE
Incorrect information in README.md about Mapper Lifetime

### ISSUE THREAD

**Issue by SDP190** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#117]
Some information in the README.md seam to be incorrect and outdated.

> Mapper instances are registered as **_transient_** as they are intended to be used within the lifetime of a request.

This sentence makes no sense, for a lifetime per request you would use Scope not **_transient_** which creates a new instance each time its used!

> To map at runtime, you'll first need a scope...

I don't see any service is using Scoped lifetime, so why would I need a Scope?

**Comment by lbargaoanu** [comment]
A PR is welcome.
