### ISSUE TITLE
Prevent consumers from not adding marker types or assemblies for profile discovery

### ISSUE THREAD

**Issue by mderriey** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#12]
I feel like it's quite easy to call `services.AddAutoMapper()` with no parameters and expect for things to Just Work™. Unfortunately, without adding at least a marker type or an assembly to drive the profile discovery, consumers will get a mapping exception later at runtime because no profiles were added to the configuration.

I guess people expect it to work since many of the *default, Microsoft-provided* extension methods do something when called with no parameters. On the other hand, I totally understand AutoMapper **needs** information to do its thing properly.

What do you think of adding a check in [this overload for marker types](https://github.com/AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection/blob/b17279bb918fee724032148390e03862196ff5a2/src/AutoMapper.Extensions.Microsoft.DependencyInjection/ServiceCollectionExtensions.cs#L161) and [this one for assemblies](https://github.com/AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection/blob/b17279bb918fee724032148390e03862196ff5a2/src/AutoMapper.Extensions.Microsoft.DependencyInjection/ServiceCollectionExtensions.cs#L176) to verify the array contains at least one element?

Or delegate it to [`AddAutoMapperClasses`](https://github.com/AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection/blob/b17279bb918fee724032148390e03862196ff5a2/src/AutoMapper.Extensions.Microsoft.DependencyInjection/ServiceCollectionExtensions.cs#L192) to check whether the initialisation action is not null **or** we have at least one assembly? But then we can't know which extension method the consumer used, hence difficult to give them a specific error message.

Just opening a discussion here, will be happy to provide a PR when/if we agree on something. As an FYI, this comes from [that SO question](http://stackoverflow.com/questions/41913764/automapper-5-2-with-inheritance-not-working/).

*Edit:*

I just realised that if in an ASP.NET Core app targeting `netcoreapp1.0`, then the `nestandard1.6` flavour is used, so calling `services.AddAutoMapper()` would call [the parameter-less overload that uses the `DependencyContext`](https://github.com/AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection/blob/b17279bb918fee724032148390e03862196ff5a2/src/AutoMapper.Extensions.Microsoft.DependencyInjection/ServiceCollectionExtensions.cs#L30). Same thing happens if the app targets the full .NET framework. I guess we should know more about the setup, then.

Unrelated question, what's the need for a `netstandard1.1` build of that library? Can the application use a `Startup` from another project which would be a class library?

**Comment by jbogard** [comment]
I've had enough problems with the overload without parameters that I'm
honestly ready to ditch it. Without AppDomains and the ability to scan the
currently loaded assemblies, this is really tough to use.

**Comment by Grepsy** [comment]
This seems to be changed since 2.0 and is causing some people (including me) to wonder what's going on, since there are examples with the parameterless method and that previously worked.

http://stackoverflow.com/questions/42916182/trying-to-add-automapper-to-netcore1-1-not-recognising-services-addautomapper

**Comment by jbogard** [comment]
Yes, it's changed. Unfortunately the compiler can't distinguish between the two overloads without anything passed in. Until I have a reliable AppDomain, we'll have to manage.
