### ISSUE TITLE
EF Core 3 has problems with automapped objects 

### ISSUE THREAD

**Issue by dh-connect** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#120]
I'm using automapper 7.0.0 together with EF Core 3.0.0. Same code worked in EF Core 2.2. 
When debugging the code automapper returns a valid and filled object, but when passing it into EF Core functions I receive Null error message exception. 

view related issue for more details:
https://github.com/aspnet/EntityFrameworkCore/issues/18735

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
