### ISSUE TITLE
Unable to add AutoMapper.Extensions.Microsoft.DependencyInjection 7.0.0

### ISSUE THREAD

**Issue by kulashaker30** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#125]
It throws exception everytime I add this version in dotnet cli.

Unable to find package AutoMapper.Extensions.Microsoft.DependencyInjection with version (>= 7.0.0)

**Comment by kulashaker30** [comment]
I am using .net core 3 btw.

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
