### ISSUE TITLE
Signed Assembly

### ISSUE THREAD

**Issue by AngelVHS** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#13]
Is there a signed version of this assembly? If not, would you be willing to produce one?

Thank you for your trouble.

**Comment by jbogard** [comment]
No and no, you can use the StrongNamer package to do so though:
https://www.nuget.org/packages/strongnamer

**Comment by AngelVHS** [comment]
Thank you for your advice but that doesn't work for me as I am referencing this assembly in a .net core project. Do you happen to know any alternative to the referred package or any work around this?

Thank you

**Comment by jbogard** [comment]
Why are you signing? Signing is not recommended by MS.

**Comment by AngelVHS** [comment]
That is for now a company requirement that I am trying to drop but for now that I must follow.
