### ISSUE TITLE
Invoking `AddAutoMapper` multiple times is not additive

### ISSUE THREAD

**Issue by goldsam** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#138]
Our project is very modular with `Profile`s defined in several different locations. The code is cumbersome due to the requirement that `AddAutoMapper` must be called in a single location exactly once. This is inconsistent with the `AddXXXX` extension methods provided by the various `Micorosft.Extensions.XXX` libraries. The result of calling `AddAutoMapper` multiple times is a silent failure where not all mapping are registered. 

It would be much more useful if mapping registrations could be registered additively by invoking `AddAutoMapper` multiple times.

**Comment by jbogard** [comment]
Have you updated? The new behavior is additive.
