### ISSUE TITLE
How do I assert that the configuration is valid?

### ISSUE THREAD

**Issue by ffMathy** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#139]
How can I assert that the configuration is valid, when this package is used to inject things via the service provider?

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by ffMathy** [comment]
Asked here: https://stackoverflow.com/questions/63260657/with-automapper-and-dependency-injection-how-can-i-assert-that-the-configuratio
