### ISSUE TITLE
DI and profiles for mapping with constructors with parameters

### ISSUE THREAD

**Issue by sanioooook** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#141]
It seems this question is repeated in part, but I did not understand the answer, so I ask again. My problem is that I need my own service for mapping, which I thought I would get in the constructor using DI, but when I try mapping, I get an error 
![image](https://user-images.githubusercontent.com/33792718/90424686-31646c00-e0c7-11ea-9b11-18303a279659.png)

AnswerMappingProfile.cs:
```C#
using AutoMapper;
using Entities.Interfaces;
using Entities.Models;
using WebApiQandA.DTO;
using WebApiQandA.Interfaces;

namespace WebApiQandA.MappersProfile
{
    public class AnswerMappingProfile: Profile
    {
        public AnswerMappingProfile(IVoteService voteService, IVoteRepository voteRepository)
        {
            CreateMap<Answer, AnswerDto>()
                .ForMember(dest => dest.Votes,
                    opt => opt
                        .MapFrom(c => voteService.GetVotesByAnswerId(c.Id)));


            CreateMap<AnswerDto, Answer>()
                .ForMember(dest => dest.Votes,
                    opt => opt
                        .MapFrom(c => voteRepository.GetVotesByAnswerId((int)c.Id)));
        }
    }
}
```

Startup.cs:

```C#
services.AddTransient<IUserService, UserService>();
services.AddTransient<ISurveyService, SurveyService>();
services.AddTransient<IAnswerService, AnswerService>();
services.AddTransient<IVoteService, VoteService>();
services.AddAutoMapper(typeof(SurveyMappingProfile), typeof(AnswerMappingProfile), typeof(VoteMappingProfile));
```
How can I solve this problem?

**Comment by sanioooook** [comment]
I found a [solution](https://stackoverflow.com/questions/44877379/how-inject-service-in-automapper-profile-class) for myself

**Comment by lbargaoanu** [comment]
https://jimmybogard.com/automapper-usage-guidelines/

X DO NOT inject dependencies into profiles

Profiles are static configuration, and injecting dependencies into them can cause unknown behavior at runtime. If you need to use a dependency, resolve it as part of your mapping operation. You can also have your extension classes (resolvers, type converters, etc.) take dependencies directly.
