### ISSUE TITLE
How can I call CompileMappings on MapperConfiguration when using AddAutomapper

### ISSUE THREAD

**Issue by DevsAnon** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#144]
Using AddAutomapper one needs only to provide assembly location of profiles.
But since I have no control and no access over MapperConfiguration, how can one call MapperCongiguration.CompileMappings()
?

**Comment by lbargaoanu** [comment]
You should inject `IConfigurationProvider` where you need it.

**Comment by jbogard** [comment]
One possibility is using a [hosted service](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-3.1&tabs=visual-studio) to run this on startup and inject the mapper configuration into that. I use that frequently for startup tasks.
