### ISSUE TITLE
Version Conflict With AutoMapper DependencyInjection and Azure Functions

### ISSUE THREAD

**Issue by chasec2018** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#147]
Hi,

There is currently a Microsoft.Extensions.DependencyInjection.Abstraction version issue with AutoMapper.Extensions.Microsoft.DependencyInjection. Currently Azure Function require Microsoft.Extensions.DependencyInjection.Abstraction v5.0.0 where as AutoMapper is using 3.0.0. As of right now the version conflict is causing errors not to load Microsoft.Extensions.DependencyInjection.Abstraction v5.0.0 and causing runtime errors. 

If you follow the link [ https://www.nuget.org/packages/Microsoft.Azure.WebJobs/ ]( https://www.nuget.org/packages/Microsoft.Azure.WebJobs/ )
--> Select the Dependencies Drop Down
--> Then select 'Microsoft.Extensions.Hosting' and select the Dependencies Drop Down again
--> and navigate to Microsoft.Extensions.DependencyInjection.Abstraction you will see they require => v5.0.0

Please let me know if this can be resolved if possible.

Thank you,

**Comment by jbogard** [comment]
What error are you getting? This sounds like an issue with Azure Functions

**Comment by chasec2018** [comment]
Hey, 

Sorry for the false alarm. After doing some further research it. It seems with the recent release of .NET 5 some of our packages got upgraded and were causing version conflicts with Microsoft DI. The issue is resolved. 

Though I do think eventually a release will be needed for .NET 5 as it seem that the version constraint is preventing backwards compatibility.

Thank you for your quick response. I apologize for my late reply.
