### ISSUE TITLE
Aligning versioning with the minimum supported version of AutoMapper

### ISSUE THREAD

**Issue by RubberChickenParadise** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#152]
Quite a few of the other projects that provide extensions for Microsoft.Extensions.DependencyInjection keep the version numbers the same between the main package and the extensions package.

Was there a reason for not following this convention for AutoMapper?

If not for the next release upgrading the version number to match the AutoMapper version number would make grabbing the right package easier.

**Comment by jbogard** [comment]
I was trying to follow SemVer.

**Comment by lbargaoanu** [comment]
While I don't use the DI package, I agree that keeping the versions in sync would make things easier, semantic versioning aside :)

**Comment by Ursanon** [comment]
+1 

It's much easier to manage packages if all versions are in sync.
Don't force user to check release notes/dates to manually pick compatible versions.

**Comment by lbargaoanu** [comment]
You only need to reference the DI package, so there's nothing manual, just NuGet.

**Comment by Ursanon** [comment]
@lbargaoanu Sure, but if you have `PackageA` with:
* `v=10.11.12`
* `v=9.10.11`
and `PackageB` with:
* `v=9.10.11`
* `v=8.9.10`

You don't have any idea what kind of configuration will work - maybe v10 of `PackageB` isn't uploaded yet?
You have to spend time checking release notes / package publish date 

TBH: it's small thing.

**Comment by jbogard** [comment]
Done! With v11.0.0
