### ISSUE TITLE
Problems restoring the latest version of the nuget package in Azure DevOps pipeline when targeting .net6

### ISSUE THREAD

**Issue by aegirorn** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#158]
I get the following error message when my pipeline is being run:

Package AutoMapper.Extensions.Microsoft.DependencyInjection 8.1.1 is not compatible with net60 (.NETFramework,Version=v6.0). Package AutoMapper.Extensions.Microsoft.DependencyInjection 8.1.1 supports: netstandard2.0 (.NETStandard,Version=v2.0) One or more packages are incompatible with .NETFramework,Version=v6.0.)

There are no problems with building projects locally.

**Comment by lbargaoanu** [comment]
It shoud [work](https://nugettools.azurewebsites.net/6.0.0-preview.3/framework-compatibility?project=net6.0&package=netstandard2.0). Make sure you're using the release version.
