### ISSUE TITLE
CS0433: The type 'ServiceCollection' exists in both ...

### ISSUE THREAD

**Issue by mattgillam** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#162]
Installing this package results in the following build error (in my Test project):

`Error CS0433: The type 'ServiceCollection' exists in both 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.Extensions.DependencyInjection, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' (CS0433)
`
would appreciate any guidance, (presumably is from conflicting dependencies), thank you.

**Comment by jbogard** [comment]
You'll likely need to create a package reference for the 6.0.0 version in your test project.

**Comment by mattgillam** [comment]
@jbogard thank you I will try that and update.

**Comment by mattgillam** [comment]
That builds, thanks for your help.
