### ISSUE TITLE
New release with latest automapper

### ISSUE THREAD

**Issue by philipp985** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#164]
Hi,
I am using the AutoMapper.Extensions.Microsoft.DependencyInjection it would be nice if you could create a new release that incorporates the latest changes. Specific the automapp 11.0.1 update. To have some of the bugfixes like Mapping with OrderBy included.
Thank you very much!

**Comment by lbargaoanu** [comment]
Try the [MyGet](https://docs.automapper.org/en/latest/The-MyGet-build.html) build.
That issue has trivial workarounds.
That being said, it's @jbogard's call.

**Comment by philipp985** [comment]
Ok, thanks. I will try that. 
It is not super urgent.. I just think it would reduce irritation. And might be just one click for you to release.
