### ISSUE TITLE
System.AggregateException

### ISSUE THREAD

**Issue by robertodalmonte** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#167]
Hi there,
when upgrading from:
		<PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="11.0.0" />
to
		<PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.0" />
I get:
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. (Status(StatusCode="Unknown", Detail="Exception was thrown by handler. NotSupportedException: Unknown collection. Consider a custom type converter from System.Byte[] to Google.Protobuf.ByteString."))
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at OneClick.Comuni.CitiesManager.get_CityList() in D:\Github\OneClick\OneClick.Comuni\CitiesManager.cs:line 30
   at OneClick.Dental.App..ctor() in D:\Github\OneClick\OneClick.Dental\App.xaml.cs:line 25
   at OneClick.Dental.App.Main()

  This exception was originally thrown at this call stack:
    [External Code]
    OneClick.Dental.Proxy.ClientChannel.GetComuneList(OneClick.Service.ComuneListRequest) in ClientChannel.cs
    OneClick.Comuni.CitiesManager.GetCityListFromServerAsync() in CitiesManager.cs

Inner Exception 1:
RpcException: Status(StatusCode="Unknown", Detail="Exception was thrown by handler. NotSupportedException: Unknown collection. Consider a custom type converter from System.Byte[] to Google.Protobuf.ByteString.")

If I roll back to version 11.0.0 everything's back to normal
Regards
Roberto

**Comment by robertodalmonte** [comment]
* from version 11.0.0 to version 12.0.0

**Comment by lbargaoanu** [comment]
You're going to have to do what the message says.
