### ISSUE TITLE
AutoMap attribute is not triggered

### ISSUE THREAD

**Issue by Danielovich** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#168]
AutoMapper.Extensions.Microsoft.DependencyInjection 12.0.0.0
.NET 6

First and foremost a big appreciation for your dedication and time spent on these things. 

We use this services.AddAutoMapper(assemblies) which calls 

```
public static IServiceCollection AddAutoMapper(this IServiceCollection services, IEnumerable<Assembly> assemblies, ServiceLifetime serviceLifetime = ServiceLifetime.Transient) 
              => AddAutoMapperClasses(services, null, assemblies, serviceLifetime);
```

And further down the chain

```
if (assembliesToScan != null)
{
....
    services.Configure<MapperConfigurationExpression>(options => options.AddMaps(assembliesToScan));
...
```

But none of my AutoMap types are being mapped accordingly.

```
[AutoMap(typeof(AnotherFkingDomainBlah))]
public class AnotherFkingDto
{....

```

The runtime error when trying to do a Mapper.Map<X, Y> is along the lines of the infamous "there is no map between X and Y".

Known issue ?

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
