### ISSUE TITLE
Question: ambigous call AddAutoMapper.

### ISSUE THREAD

**Issue by Allann** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#17]
I just upgraded to AutoMapper 6.0.0 and this assembly (2.0.0) and now receive the error:

> The call is ambiguous between the following methods or properties: 'ServiceCollectionExtensions.AddAutoMapper(IServiceCollection, Action<IMapperConfigurationExpression>, params Assembly[])' and 'ServiceCollectionExtensions.AddAutoMapper(IServiceCollection, Action<IMapperConfigurationExpression>, params Type[])'	Jbssa.FreightRates.Web	d:\jbs\FreightRates\src\Jbssa.FreightRates.Web\Startup.cs

The specific line of code is:
```
services.AddAutoMapper(cfg =>
{
     cfg.CreateMap<DateTimeOffset, DateTime>().ConvertUsing<DateTimeOffsetConverter>();
     cfg.CreateMap<DateTime, DateTimeOffset>().ConvertUsing<DateTimeConverter>();
     cfg.CreateMap<DateTimeOffset?, DateTime?>().ConvertUsing<NullableDateTimeOffsetConverter>();
     cfg.CreateMap<DateTime?, DateTimeOffset?>().ConvertUsing<NullableDateTimeConverter>();
});
```

This hasn't changed for a while and is being used in many projects.  What solution would you recommend?

I also tried the follwoing with the same issue:

```
private class DateProfile : Profile
{
    public DateProfile()
    {
        CreateMap<DateTimeOffset, DateTime>().ConvertUsing<DateTimeOffsetConverter>();
        CreateMap<DateTime, DateTimeOffset>().ConvertUsing<DateTimeConverter>();
        CreateMap<DateTimeOffset?, DateTime?>().ConvertUsing<NullableDateTimeOffsetConverter>();
        CreateMap<DateTime?, DateTimeOffset?>().ConvertUsing<NullableDateTimeConverter>();
     }
}

public void ConfigureServices(IServiceCollection services)
{
    services.AddAutoMapper(cfg => cfg.AddProfile(new DateProfile()));
}
```

**Comment by jbogard** [comment]
You need to pass in the assemblies to scan for now - the existing implementation was broken and rather than try to get a less-broken-version, I just took it out. So do something like:

```
services.AddAutoMapper(typeof(Startup), cfg =>
{
     cfg.CreateMap<DateTimeOffset, DateTime>().ConvertUsing<DateTimeOffsetConverter>();
     cfg.CreateMap<DateTime, DateTimeOffset>().ConvertUsing<DateTimeConverter>();
     cfg.CreateMap<DateTimeOffset?, DateTime?>().ConvertUsing<NullableDateTimeOffsetConverter>();
     cfg.CreateMap<DateTime?, DateTimeOffset?>().ConvertUsing<NullableDateTimeConverter>();
});
```

**Comment by Allann** [comment]
When I use the command I get the compile error:

> cannot convert from 'System.Type' to 'System.Reflection.Assembly'	Jbssa.FreightRates.Web..NETCoreApp,Version=v1.0	C:\TFS2015\Scorecard\Dev\Jbssa.FreightRates\src\Jbssa.FreightRates.Web\Startup.cs	42

I get the following error:

> Cannot convert lambda expression to type 'Assembly[]' because it is not a delegate type	Jbssa.FreightRates.Web..NETCoreApp,Version=v1.0	C:\TFS2015\Scorecard\Dev\Jbssa.FreightRates\src\Jbssa.FreightRates.Web\Startup.cs	41

Swapping the order of the parameters:
```
            services.AddAutoMapper(cfg =>
                {
                    cfg.CreateMap<DateTimeOffset, DateTime>().ConvertUsing<DateTimeOffsetConverter>();
                    cfg.CreateMap<DateTime, DateTimeOffset>().ConvertUsing<DateTimeConverter>();
                    cfg.CreateMap<DateTimeOffset?, DateTime?>().ConvertUsing<NullableDateTimeOffsetConverter>();
                    cfg.CreateMap<DateTime?, DateTimeOffset?>().ConvertUsing<NullableDateTimeConverter>();
                }, typeof(Startup));
```

Fixed the compile error, but when I execute the application, get the following exception:

> Missing type map configuration or unsupported mapping.

This is possibly because my TypeConverters exist in a different DLL and not in the MVC application.
I altered the line again adding additional types from each DLL that contains profiles and things started to work again as expected.

```
                .AddAutoMapper(cfg =>
                {
                    cfg.CreateMap<DateTimeOffset, DateTime>().ConvertUsing<DateTimeOffsetConverter>();
                    cfg.CreateMap<DateTime, DateTimeOffset>().ConvertUsing<DateTimeConverter>();
                    cfg.CreateMap<DateTimeOffset?, DateTime?>().ConvertUsing<NullableDateTimeOffsetConverter>();
                    cfg.CreateMap<DateTime?, DateTimeOffset?>().ConvertUsing<NullableDateTimeConverter>();
                }, typeof(DateTimeConverter), typeof(CarrierMapping), typeof(Startup))
```
I think this change was a step backwards and hope we will soon see the old implementation again.

**Comment by jbogard** [comment]
So it'll come back, once AppDomain is back. The current implementation is
broken in that it can't be used in any unit tests.
