### ISSUE TITLE
Resolving of Profiles using DI

### ISSUE THREAD

**Issue by AlexanderGurinov** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#18]
Hello, gentlemen.
Thank you for a Great Tool.
Is it possible to add a resolving of profiles with DI? When I am trying to use `.AddAutoMapper(expression => expression.AddProfile<AutoMapperProfile>)` extension method, it requires an parameterless constructor because of `where TProfile : Profile, new()` restriction in the IMapperConfigurationExpression interface. Also I can't add an instance of my AutoMapperProfile class with .AddProfile(autoMapperProfile), because of resolving of a profiles by their types anyway ( https://github.com/AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection/blob/master/src/AutoMapper.Extensions.Microsoft.DependencyInjection/ServiceCollectionExtensions.cs#L206). As workaround  I am using this approach:
```
.AddTransient<IMapper>(provider => new Mapper(new MapperConfiguration(expression => expression.AddProfile(provider.GetService<AutoMapperProfile>()))))
.AddTransient<AutoMapperProfile>()
```
but it would be nice to use out of the box .AddAutoMapper method from ServiceCollectionExtensions.
Thanks a lot

**Comment by jbogard** [comment]
Why would you need profiles instantiated from DI? Whenever I see that, it's generally someone doing something wrong that would be better served with a value resolver/type converter that IS resolved via DI.

**Comment by lbargaoanu** [comment]
That's a different repository.

**Comment by AlexanderGurinov** [comment]
Let me explain why I need to use DI in my mapper profile. I am using Dynamics Crm to map from Entity type to my destination model. This Entity type have a lookup to another Entity which have some properties, which I store in my model. This lookup can be null. But when it is not null, I need to read properties from this lookup and map them into my model. Lookup contains only Id, so I need to send an extra request to Dynamics service. So I am injecting a Dynamics service into AutoMapperProfile to do such kind of requests. If I will use converter, I need to pass a Dynamics service into converter anyway. So I decided to avoid of using custom converters and store all mapping logic in the AutoMapperProfile.

**Comment by AlexanderGurinov** [comment]
Thank you for directing me. I am added a type converter and it worked perfectly with injected service into constructor.
Initially I was confused with such behaviour of `.AddProfile(autoMapperProfile)` method because I am passed ready to use instance of a mapper profile and I did not expect, that it will be acivated with parameterless constructor anyway. I will use a type converter, but it would be great to add a support of using already instantiated profile.

**Comment by jbogard** [comment]
Eh?

https://github.com/AutoMapper/AutoMapper/blob/master/src/AutoMapper/Configuration/MapperConfigurationExpression.cs#L37

I don't _think_ I force a no-arg ctor if you pass in an instance of a profile, it just stores it internally.

**Comment by AlexanderGurinov** [comment]
I think that in https://github.com/AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection/blob/master/src/AutoMapper.Extensions.Microsoft.DependencyInjection/ServiceCollectionExtensions.cs#L208
called this method:
https://github.com/AutoMapper/AutoMapper/blob/master/src/AutoMapper/Configuration/MapperConfigurationExpression.cs#L44

**Comment by AlexanderGurinov** [comment]
After some additional investigation I understood that I am faced with a semantic kind of problem.
Thank you for patience :)

**Comment by jbogard** [comment]
Oh, yeah. That's one that's suuuuuuper easy to abuse which is why I tried
to disallow it. People leaving DbContexts open and the like.
