### ISSUE TITLE
Where condition in scanning of dependency context breaks compatibility with msbuildproject types

### ISSUE THREAD

**Issue by c-s-n** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#2]
**Background**
We have a Visual Studio solution with multiple projects. The main project is an ASP.NET Core Web Application, which currently solely targets .NET Framework. The other projects are partly .NET Core Class Libraries (also only targeting .NET Framework) and normal Class Libraries (especially for COM interop services).
So far we used to have AutoMapper automatically scan the assemblies of the default DependencyContext for any contained profiles etc.

**Problem**
With the latest changes for version 1.1.0, in particular [this commit](https://github.com/AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection/commit/9543bae7e4a6ba793673a74fd743e86e4e0f2e45), the compatibility with normal Class Libraries has been broken. These are not contained any more in the list of assemblies to scan, even if they reference the AutoMapper library and contain profiles etc.

**Cause**
The problem comes from the fact that the `RuntimeLibrary.Dependencies` for these libraries does only contain other normal Class Libraries, not the AutoMapper assembly. The `Where` condition thus excludes these.

**Suggestion**
You could handle the normal Class Libraries differently (i.e. always include them), notable from the  different `Type` they have, being "msbuildproject". The .NET Core ones have "project".

**Comment by jbogard** [comment]
Ohhh that's interesting. Could you show me a quick repro? Zip file or something?

**Comment by c-s-n** [comment]
I have created a repro project for you: [AutoMapperScanning.zip](https://github.com/AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection/files/447223/AutoMapperScanning.zip)

You will note that the `ClassLibrary` `ModelProfile` constructor is not called and thus the mapping in the `Main` method (there for least project complexity) only succeeds for the `ClassLibraryCore` models.
I also build a quick enumeration of the `RuntimeLibraries`, printing out the problematic parts.
