### ISSUE TITLE
Suggestion: IMapper<T>

### ISSUE THREAD

**Issue by fubar-coder** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#20]
We have somewhat special requirements in our application:

1. We need to map the same src/dst type pairs differently in different parts of our project
2. We need access to a scoped `IServiceProvider` in our mappings

The proposed solution to those problems is having a default `IMapper<T> where T : IConfigurationProvider` or something similar.

We evaluated the following implementations:

* `IMapper<T> where T : IConfigurationProvider`

   This seems to be the most flexible solution.

* `IMapper<T> where T : Profile`

   There doesn't seem to be a way to merge profiles by using `AddProfile` from within a profile which makes this solution unusable.

* `IMapper<T1> where T : Profile` and overloads with `IMapper<T1, T2>`, etc...

   Too much boilerplate for us.

The implementation with `T : IConfigurationProvider` was the most flexible for us even though we need (in the worst case) both a `IConfigurationProvider` implementation and a `Profile` derived class for a single mapping, like e.g.:

```csharp
public class MyProfile1 : Profile
{
    public MyProfile1()
    {
        // Mapping configuration
    }
}
```

Someone would be able to create its own class derived from `MapperConfiguration`:

```csharp
public class MyConfiguration : MapperConfiguration
{
    public MyConfiguration(MyProfile profile)
        : base(cfg => cfg.AddProfile(profile))
    {
    }
}
```

A generic implementation of a profile configuration could look like this (even though I don't really like this solution):

```csharp
public class ProfileConfiguration<T> : MapperConfiguration where T : Profile
{
    public ProfileConfiguration(T profile)
        : base(cfg => cfg.AddProfile(profile))
    {
    }
}

public class ProfileConfiguration<T1, T2> : MapperConfiguration where T1 : Profile, T2 : Profile
{
    public ProfileConfiguration(T1 profile1, T2 profile2)
        : base(cfg => { cfg.AddProfile(profile1); cfg.AddProfile(profile2); })
    {
    }
}
```

We add all classes derived from `MapperConfiguration` and `Profile` to our service collection which allows us to use `IMapper<MyConfiguration>` (or `IMapper<ProfileConfiguration<MyProfile>>`) in a constructor which gets resolved to `Mapper<MyConfiguration>` (or `Mapper<ProfileConfiguration<MyProfile>>`) which looks like this:

```csharp
public class Mapper<T> : IMapper<T>
    where T : IConfigurationProvider
{
    private readonly IMapper _mapper;

    public Mapper(IServiceProvider serviceProvider, T t)
    {
        _mapper = new Mapper(t, serviceProvider.GetService);
    }

    public IConfigurationProvider ConfigurationProvider => _mapper.ConfigurationProvider;

    // ... remaining implementation
```

All those types are registered with:
```csharp
serviceCollection
    .Scan(scan => scan.FromAssemblyOf<Startup>().AddClasses(c => c.AssignableTo<Profile>()).AsSelf().WithSingletonLifetime())
    .Scan(scan => scan.FromAssemblyOf<Startup>().AddClasses(c => c.AssignableTo<IConfigurationProvider>()).AsSelf().WithSingletonLifetime())
    .AddScoped(typeof(IMapper<>), typeof(Mapper<>))
```

The `Scan` function is from the [Scrutor package](https://github.com/khellang/Scrutor). This project would/should probably avoid using Scrutor and use its own implementation instead (as it already does).

The usage would look like this:

```csharp
public class MyController
{
    public MyController(IMapper<MyConfiguration> mapper)
    {
    }
}
```

**Comment by jbogard** [comment]
Hrmmmmm. I think this is really "named instances", which MS DI does not support AFAIK. You'd want to use a "Real DI Container" for this kind of behavior.
