### ISSUE TITLE
Referencing an assembly

### ISSUE THREAD

**Issue by gforceg** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#22]
Hello,

I'm using this package in my dotnet core application and I don't understand how to reference an assembly this way: `services.AddAutoMapper(<my_assembly>)`

The only way I know how to reference an assembly is with the `using` keyword. I realize this is probably a C# question and not a question about this package, but google keeps pointing me to the `using` keyword. 

I'm looking for the magic words to search for in google or a concrete example I can study that uses  `services.AddAutoMapper(<some_assembly_in_a_solution>)`?

Thanks.

**Comment by lbargaoanu** [comment]
Check out the [tests](https://github.com/AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection/tree/3d494875afe8ee20ff3460933d3e8e17a481f7f6/test/AutoMapper.Extensions.Microsoft.DependencyInjection.Tests).

**Comment by gforceg** [comment]
Thanks that was helpful!
I completely misunderstood how to use this library before following your advise.
