### ISSUE TITLE
.Net core DI and the static mapper

### ISSUE THREAD

**Issue by gdahlin** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#23]
Just coming from AutoMapper/AutoMapper#2140 I actually got my setup to work as initially expected.

Although, when using static mapping after having done: 

`services.AddAutoMapper()
        .AddTransient<CustomResolver, DefaultCustomResolver>();`

The mapping configuration looks like:

```csharp
...
.ForMember(dest => dest.SomeDate, opt => opt.ResolveUsing<CustomResolver>())
``` 

Ends up with the following stacktrace when mapping with Mapper.Map :

`at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
         at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
         at System.Activator.CreateInstance(Type type, Boolean nonPublic)
         at System.Activator.CreateInstance(Type type)
         at AutoMapper.MappingOperationOptions2.CreateInstance[T]()
         at lambda_method...`

It seems that the static mapper does not get/uses the IServiceProvider.GetService method supplied when setting up the IMapper instance in .AddAutoMapper()?

Injecting and using the IMapper instance and doing the same mapping works as expected with the injected Resolver.

**Comment by lbargaoanu** [comment]
I think it doesn't even try to do that, so that's a feature request.

**Comment by gdahlin** [comment]
Now when I got everything to run as expected it's not super crucial, but for those wanting the same thing regarding to resolvers and for instance are relying on projections in their code this might be important?

**Comment by lbargaoanu** [comment]
For ProjectTo it's not relevant.

**Comment by jbogard** [comment]
No, and it shouldn't. If you want to use DI with value resolvers and the like, you MUST inject an IMapper instance. Mixing static with DI is a very bad idea, and the MS DI is designed to correctly build up scopes that I take advantage of.

In short, do not mix DI and static mapper. Inject an IMapper.
