### ISSUE TITLE
IValueResolver DI issues

### ISSUE THREAD

**Issue by gforceg** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#24]
Hello,

I'm having issues injecting IHttpContextAccessor into my custom value resolver. When I try to inject the service using the default dotnet core DI, AutoMapper seems to expect that my resolver uses a default constructor and I get the error message: `Property:
Url ---> System.MissingMethodException: No parameterless constructor defined for this object.`

This is the call in my profile that is throwing the exception:

``` C#
      CreateMap<AppointmentType, AppointmentTypeViewModel>()
      .ForMember(model => model.Url,
      opt => opt.ResolveUsing<SolutionUrlResolver>())
      .ReverseMap();
```

Here's my Resolver:
``` C#
namespace View
{
  public class SolutionUrlResolver : IValueResolver<SolutionEntity, SolutionViewModel, string>
  {
    public const string URLNAME = "GetAppointmentTypes";
    private IHttpContextAccessor _httpContextAccessor;

    public SolutionUrlResolver(IHttpContextAccessor httpContextAccessor) {
      _httpContextAccessor = httpContextAccessor;
    }

    public string Resolve(SolutionEntity source, SolutionViewModel destination, string destMember, ResolutionContext context)
    {
      var url = (IUrlHelper)_httpContextAccessor.HttpContext.Items[BaseController.URLHELPER];
      return url.Link(URLNAME, new { id = source.Id});
    }
  }
}
```

In Startup.cs I have this:
```
    public void ConfigureServices(IServiceCollection services)
    {
      services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();
      services.AddAutoMapper();
      services.AddMvc(); ...
```
 When I replace the SolutionUrlResolver with a class that uses a default constructor (and does not reference IHttpContextAccessor) then the exception goes away.

I tried mimicking the way DependencyResolver is written in the test app. I must be missing something simple here but I just don't know what it is.

**Comment by jbogard** [comment]
Can you try the AddAutoMapper overload that takes the assembly/types to scan? I fear that that overload didn't pick up the value resolver.

Also, make sure you're using the injected IMapper, not the static mapper.

**Comment by gforceg** [comment]
> Also, make sure you're using the injected IMapper, not the static mapper.

That was it! While I did inject IMapper into my controller, I was calling 'AutoMapper.Mapper'.

Thank you for pointing me in the right direction, it feels like I've been trying to troubleshoot this one issue all day today!
