### ISSUE TITLE
DI within the profiles?

### ISSUE THREAD

**Issue by mattwoberts** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#29]
For one of my mappings, I need access to some configuration element, so ideally I'd love to be able to do this:

    public class MappingProfile : Profile 
    {
        public MappingProfile(IOptions<Settings> options) {

            CreateMap<User, EditUserModel>(MemberList.Source)
                .ForMember(m => m.Something,
                    o => o.MapFrom(a => a.GenerateThing(options.SomeConfigItem)));

But that's not supported - can you advise how I might achieve this?

Thanks

**Comment by lbargaoanu** [comment]
Yes, create the profiles using your container :) See also https://github.com/AutoMapper/AutoMapper/issues/2208.

**Comment by mattwoberts** [comment]
Thanks :) So from looking at that related issue, it seems I need to use a DI-resolved value resolver in order to get my parameter, I'll look into that
