### ISSUE TITLE
AssertConfigurationIsValid not working into extension method AddAutoMapper

### ISSUE THREAD

**Issue by rdcm** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#33]
I'm trying configure Automapper at Startup.cs, but AssertConfigurationIsValid not actually do at application start.

```
            services.AddAutoMapper(cfgExpression => 
            { 
                cfgExpression.AddProfile<MappingProfile>(); 
                cfgExpression.Advanced.BeforeSeal(cfgProvider => cfgProvider.AssertConfigurationIsValid<MappingProfile>());
            });
```

If add `Mapper.Configuration.AssertConfigurationIsValid();` after call extension `AddAutoMapper` AssertConfiguration works as expected.

Is this the correct behavior?

**Comment by lbargaoanu** [comment]
You're supposed to call AssertConfigurationIsValid after the init phase is over.

**Comment by rdcm** [comment]
Ok, is it possible configure automapper without calling static class `Mapper`, only by extension method?

**Comment by lbargaoanu** [comment]
I don't think so, but it's easy to write your own extension method that does what you want.

**Comment by rdcm** [comment]
Yes, custom extension solve my problem, but is it possible to add this behavior to AutoMapper.Extensions?

**Comment by jbogard** [comment]
You could do that, but it makes ProjectTo a bit more annoying since those are static extension methods. I'd just add your own extension method if you don't want the default behavior.

Alternatively, you can grab the configuration provider from the services collection and call `AssertConfigurationIsValid` on it.

**Comment by jbogard** [comment]
I'm adding this as an option, see #38
