### ISSUE TITLE
Dependecy Injection inside Profile Classes

### ISSUE THREAD

**Issue by DavidNorena** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#34]
Hi, is there a way you can change the code in this line [here](https://github.com/AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection/blob/master/src/AutoMapper.Extensions.Microsoft.DependencyInjection/ServiceCollectionExtensions.cs#L84) so we can also inject services inside profiles ?

**Comment by jbogard** [comment]
What service? The only thing you could is just static config.

**Comment by DavidNorena** [comment]
I was taking a wrong approach ! thanks for your time !
