### ISSUE TITLE
The new version 3.x.x doesn't find Profile classes.

### ISSUE THREAD

**Issue by EduardoPires** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#35]
@jbogard 

I upgraded my project to V3.x.x and it crashes in the mapping like:
`Mapper.Map<model1>(model2);`

I have the services.AddAutoMapper(); at Startup.cs and my profile classes with Profile class inheritance.

I did the downgrade to 2.0.1 and it started to work fine again.

What changed? It's a bug or have new way to configure?

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection/blob/master/README.md

**Comment by EduardoPires** [comment]
I get it!
Why the automatic discovery of profiles was removed?

**Comment by lbargaoanu** [comment]
I think there was no reliable way to make it work.

**Comment by EduardoPires** [comment]
In the v2.0.1 works fine for me. 
For curiosity I'd like to understand if the removal of automatic discovery was due a design flaw or something like that.

**Comment by jbogard** [comment]
3.0.1 should work, I loop over the AppDomain assemblies. Can you try that?
