### ISSUE TITLE
What's the point of using the package?

### ISSUE THREAD

**Issue by SuperJMN** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#39]
I don't want to sound rough, but I would like to know a sample usage to understand why anyone would use this.

What are the benefits of injecting AutoMapper into the DI mechanism of ASP.NET Core? Does it make AutoMapper able to construct object with dependencies using the integrated ASP.NET's DI container? 

For now, the only think I have seen is that I can inject an instance of the mapper using a IMapper mapper in the constructor of my controller, but that doesn't offer much advantages. Previously, I used the state Mapper façade.

**Comment by lbargaoanu** [comment]
https://lostechies.com/jimmybogard/2016/07/20/integrating-automapper-with-asp-net-core-di/

**Comment by SuperJMN** [comment]
@ibargaoanu Thanks, but the post doesn't show how to use it, but how Jimmy was able to integrate AutoMapper with ASP.NET Core's IoC DI built-in container. I still don't understand what are the benefits of doing so. Can you please provide some information on hoe this is useful?

**Comment by lbargaoanu** [comment]
I think you should actually read the thing. It starts with the problem.
