### ISSUE TITLE
Required explicit dependency on Automapper

### ISSUE THREAD

**Issue by cmdkeen** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#4]
Probably an odd one that no-one else will run into...

If I have only "AutoMapper.Extensions.Microsoft.DependencyInjection" defined in the dependencies section of a project.json the project will compile and run but not pick up any assemblies to load configuration from.

Adding an explicit reference to "AutoMapper" to the project.json fixes this.

This is due to https://github.com/AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection/blob/master/src/AutoMapper.Extensions.Microsoft.DependencyInjection/ServiceCollectionExtensions.cs#L31

I don't think a change to code is required, though it might be worth adding something to the Readme / any tutorials to explicitly reference AutoMapper.

**Comment by jbogard** [comment]
Welp, this is a bug
