### ISSUE TITLE
[Feature Request] Add IApplicationBuilder Extension Method For Mapper.AssertConfigurationIsValid() Functionality

### ISSUE THREAD

**Issue by wdspider** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#43]
Would it be possible to add an IApplicationBuilder extension method that adds the functionality that `Mapper.AssertConfigurationIsValid()` provided to non .NET Core based projects?

I'm envisioning my Startup class to look something like this:
```
public class Startup
{
	public void ConfigureServices(IServiceCollection services)
	{
		services.AddAutoMapper(typeof(MyMappingProfile));
	}
	
	public void Configure(IApplicationBuilder app, IHostingEnvironment env)
	{
		if (env.IsDevelopment())
		{
			app.UseDeveloperExceptionPage();
			app.AssertAutoMapperConfigurationIsValid();
		}
	}
}
```

Ideally, this would make the assert exceptions to be thrown when a request is made to the server in much the same way that adding `Mapper.AssertConfigurationIsValid()` to `Global.asax - Application_Start()` in .NET based projects did.

NOTE:  I did attempt to simply use `Mapper.AssertConfigurationIsValid()`; however, it did not assert properly.  I assume this is due to needing to use the non-static IMapper which does not currently have the `AssertConfigurationIsValid()` method.

**Comment by jbogard** [comment]
PR?

**Comment by wdspider** [comment]
I'm at a lost at how to get `AssertConfigurationIsValid()` to properly work in the `Configure()` method particularly since it does not seem to be a part of the `IMapper` interface.  As such, I currently don't have a starting point for a PR.

**Comment by jbogard** [comment]
No it’s part of the configuration interfaces, which are registered also.
Check the registration code.

**Comment by wdspider** [comment]
I've gone ahead and submitted Pull Request #44 for review.

**Comment by StevenLiekens** [comment]
Please reopen because #44 was reverted in #61

I'm still looking for a solution for this that isn't copy-pasting the code from #44 into every aspnet core project

**Comment by jbogard** [comment]
If you find a solution that doesn’t pull in ASP.NET Core, I’m happy to add
it back in.

**Comment by fchiumeo** [comment]
```cs
app.Use(async (context, next) =>
{
   await next();
   context.RequestServices.GetService<IMapper>().ConfigurationProvider.AssertConfigurationIsValid();
});

**Comment by StevenLiekens** [comment]
Correct me if I'm wrong but middleware is not the right tool for this anyway because there's no point in validating the configuration for every request.

**Comment by jbogard** [comment]
@StevenLiekens yep, you only want to do it once, and at startup.

**Comment by StevenLiekens** [comment]
I'm (ab)using `IHostedService` right now

```c#
public class AssertConfigurationIsValidService : IHostedService
{
    private readonly IConfigurationProvider _configurationProvider;

    public AssertConfigurationIsValidService(IConfigurationProvider configurationProvider)
    {
        _configurationProvider = configurationProvider ??
                                    throw new ArgumentNullException(nameof(configurationProvider));
    }

    public Task StartAsync(CancellationToken cancellationToken)
    {
        _configurationProvider.AssertConfigurationIsValid();
        return Task.CompletedTask;
    }

    public Task StopAsync(CancellationToken cancellationToken)
    {
        // nothing to do here
        return Task.CompletedTask;
    }
}
```

That pulls in https://www.nuget.org/packages/Microsoft.Extensions.Hosting.Abstractions/

**Comment by StevenLiekens** [comment]
I've spent way more time on this than I should have but I'm now convinced that I found the best way to do this:

```c#
public void ConfigureServices(IServiceCollection services)
{
    services.AddAutoMapper();
}

public void Configure(IApplicationBuilder app, IHostingEnvironment env, IConfigurationProvider automapper)
{
    automapper.AssertConfigurationIsValid();
}
````

Okay so for anyone who didn't know (I didn't), any parameter in the `Configure()` method will be resolved from your `IServiceCollection`. So you can get an instance of `IConfigurationProvider` just by asking for one.

**Comment by jbogard** [comment]
Ha! Would you mind editing the Readme to add a little snippet about this?

**Comment by StevenLiekens** [comment]
Done -> #63

**Comment by wdspider** [comment]
Sorry for the late reply, I was on vacation.

@StevenLiekens While I was aware you could add special framework parameters to Configure that it would bind, I was aware that it would work for anything in the IServiceCollection. That's a pretty cool find and makes the code much simpler 👍
