### ISSUE TITLE
AutoMapper.Extensions.Microsoft.DependencyInjection Dependency on custom Resolver not working in ASP.NET Core 2.0 project

### ISSUE THREAD

**Issue by filipesatti** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#46]
In my ASPNET Core 2.0 project, when adding a Cache Dependency to my CustomResolver, such dependency is not resolved. I have a complex dependency structure and many mapping profiles which I register as below:

`
services.AddSingleton<ICacheService, CacheService>();
            var config = new MapperConfiguration(cfg =>
            {
                cfg.AddProfile(new CreateProductProfile());
                cfg.AddProfile(new ChangeProductProfile());
                cfg.AddProfile(new SharedProfile());
                cfg.AddProfile(new RetrieveProductProfile());
            });

            var mapper = config.CreateMapper();
            services.AddSingleton(mapper);
`
My resolver CustomResolver has below code:

`
public class ProductIdResolver : IValueResolver<Request.Product, Entities.Product, int>
    {
        private readonly ICacheService cacheService;

        public ProductIdResolver(ICacheService cacheService)
        {
            this.cacheService = cacheService;
        }

        public Entities.Product Resolve(Request.Product source, Entities.Product destination, int destMember, ResolutionContext context)
        {
            if (source == null)
                return null;

            var product = Mapper.Map<Entities.Product>(source);

            product.Id = TranformProductId(source);

            return product;
        }

        private int TranformProductId(Request.PBI source)
        {
            var frombase = cacheService.GetProducts().FirstOrDefault(p => p.Sku == source.Sku);

            if (frombase == null)
                throw new NullReferenceException("Invalid Product");

            return frombase.Id;
        }
    }

`

The resolver reference is inside my SharedProfile, which is called by both Create and Change profile (I broke those profile classes into a third one for code re-using).
The problem is that my CacheService is not being resolved by DI and I always get an "Error mapping types" exception.
For reference, my code works if I remove the CacheService object.

How can I successfully inject that dependency into my custom resolver?

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection/blob/master/README.md
https://lostechies.com/jimmybogard/2016/07/20/integrating-automapper-with-asp-net-core-di/

**Comment by filipesatti** [comment]
Thanks for quick response!

I tried to change my code as per documentation and followed the instructions in "integrating automapper with asp net code di" link:

`services.AddAutomapper(typeof(Startup))`

However, I am still facing the same error message... 
I am new to .Net Core and DI stuff, probably I'm still doing something wrong

in your link, there is a similar sample to my code for the resolver depending on a dbcontext.
Is there anything else I should change to configure automapper in my startup class or in the SharedProfile.cs?

Thanks in Advance!

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
