### ISSUE TITLE
DI into ITypeConverter

### ISSUE THREAD

**Issue by imperugo** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#47]
Hi, 
I'm trying to inject a service into a ITypeConverter but it doesn't work.
To be more specific I'm getting this message:

```console
Mapping types:
Source2 -> Dest2
TestApp.Source2 -> TestApp.Dest2

Type Map configuration:
Source2 -> Dest2
TestApp.Source2 -> TestApp.Dest2

Property:
ResolvedValue ---> System.MissingMethodException: No parameterless constructor defined for this object.
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at AutoMapper.MappingOperationOptions`2.CreateInstance[T]()
   at lambda_method(Closure , Object , Object , ResolutionContext )
   --- End of inner exception stack trace ---
   at lambda_method(Closure , Object , Object , ResolutionContext )
   at AutoMapper.Mapper.AutoMapper.IMapper.Map[TDestination](Object source)
   at TestApp.Program.Main(String[] args) in C:\Projects\OpenSource\AutoMapper.Extensions.Microsoft.DependencyInjection\src\TestApp\Program.cs:line 24}	AutoMapper.AutoMapperMappingException
```

What I did to replicate this problem is to extend the test class included into the repo with this:

```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TestApp
{
	using System.Reflection;
	using AutoMapper;
	using Microsoft.Extensions.DependencyInjection;
	using System.Threading;
	using System.Threading.Tasks;

	public class Program
	{
		public static void Main(string[] args)
		{
			IServiceCollection services = new ServiceCollection();
			services.AddTransient<ISomeService>(sp => new FooService(5));
			services.AddAutoMapper(typeof(Source));
			var provider = services.BuildServiceProvider();
			var mapper = provider.GetService<IMapper>();

			var result = Mapper.Map<Dest2>(new Source2()
			{
				Text = new MyComplexType()
				{
					Text = "Ciao",
				}
			});

			foreach (var service in services)
			{
				Console.WriteLine(service.ServiceType + " - " + service.ImplementationType);
			}
			Console.ReadKey();
		}
	}

	public class Source
	{
	}

	public class Dest
	{
	}

	public class Source2
	{
		public MyComplexType Text { get; set; }
	}

	public class Dest2
	{
		public int ResolvedValue { get; set; }
		public string LocalizedValue { get; set; }
	}

	public class Profile1 : Profile
	{
		public Profile1()
		{
			CreateMap<Source, Dest>();
		}
	}

	public class Profile2 : Profile
	{
		public Profile2()
		{
			CreateMap<Source2, Dest2>()
				.ForMember(d => d.ResolvedValue, opt => opt.ResolveUsing<DependencyResolver>());
		}
	}

	public class DependencyResolver : IValueResolver<object, object, int>
	{
		private readonly ISomeService _service;

		public DependencyResolver(ISomeService service)
		{
			_service = service;
		}

		public int Resolve(object source, object destination, int destMember, ResolutionContext context)
		{
			return _service.Modify(destMember);
		}
	}

	public interface ISomeService
	{
		int Modify(int value);
	}

	public class FooService : ISomeService
	{
		private readonly int _value;

		public FooService(int value)
		{
			_value = value;
		}

		public int Modify(int value) => value + _value;
	}

	public class MyComplexTypeStringConverter : ITypeConverter<MyComplexType, string>
	{
		private readonly ISomeService service;

		public MyComplexTypeStringConverter(ISomeService service)
		{
			this.service = service;
		}

		public string Convert(MyComplexType source, string destination, ResolutionContext context)
		{
			return source.Text;
		}
	}

	public class MyComplexType
	{
		public string Text { get; set; }
	}
}

```

I'm pretty sure I did something wrong, but what?
Thanks

**Comment by lbargaoanu** [comment]
Try ```ResolveUsing<Interface>()```

**Comment by imperugo** [comment]
AFAIK `ResolveUsing<T>` needs a `IValueResolver` but I'm trying to use a `ITypeConverter`

**Comment by lbargaoanu** [comment]
Where is that, I don't see it :)

**Comment by imperugo** [comment]
here

https://github.com/AutoMapper/AutoMapper/blob/master/src/AutoMapper/IMemberConfigurationExpression.cs#L32

**Comment by imperugo** [comment]
I also tried this:

```
CreateMap<MyComplexType, string>().ConvertUsing<MyComplexTypeStringConverter>();
```

but same result

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by imperugo** [comment]
LOL

**Comment by jbogard** [comment]
What is the output of the console?

**Comment by imperugo** [comment]
Here the output

```Console
TestApp.ISomeService -
TestApp.DependencyResolver - TestApp.DependencyResolver
TestApp.MyComplexTypeStringConverter - TestApp.MyComplexTypeStringConverter
AutoMapper.IConfigurationProvider -
AutoMapper.IMapper -
```

**Comment by lbargaoanu** [comment]
Try ```mapper``` instead of ```Mapper```.

**Comment by imperugo** [comment]
With `mapper` there are no error, but the code doesn't enter into my `MyComplexTypeStringConverter`

**Comment by lbargaoanu** [comment]
What can I say, take it step by step, do it without DI, see that it works, then add the DI stuff. The tests are [here](https://github.com/AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection/tree/master/test/AutoMapper.Extensions.Microsoft.DependencyInjection.Tests).

**Comment by imperugo** [comment]
I found a work around in my application in this way:

```csharp
internal static class AutomapperExtensions
	{
		private static readonly TypeInfo[] allTypes;

		static ServiceCollectionExtensions()
		{
			allTypes = Core.Constants.MyAssemblies
				.SelectMany(a => a.DefinedTypes)
				.ToArray();
		}

		public static void AddAutomapper(this IServiceCollection services)
		{
			var openTypes = new[]
			{
				typeof(IValueResolver<,,>),
				typeof(IMemberValueResolver<,,,>),
				typeof(ITypeConverter<,>),
				typeof(IMappingAction<,>)
			};

			foreach (var type in openTypes.SelectMany(openType => allTypes
				.Where(t => t.IsClass 
				            && !t.IsAbstract 
				            && t.AsType().ImplementsGenericInterface(openType))))
			{
				services.AddTransient(type.AsType());
			}
		}

		public static void UseAutoMapper(this IApplicationBuilder app)
		{
			var profiles = allTypes
								.Where(t => typeof(Profile).GetTypeInfo().IsAssignableFrom(t.GetTypeInfo()))
								.Where(t => !t.GetTypeInfo().IsAbstract)
								.ToArray();

			Mapper.Initialize(cfg =>
			{
				cfg.ConstructServicesUsing(app.ApplicationServices.GetService);

				foreach (var profile in profiles)
				{
					cfg.AddProfile(profile);
				}
			});

			Mapper.Configuration.AssertConfigurationIsValid();
		}

		private static bool ImplementsGenericInterface(this Type type, Type interfaceType)
		{
			return type.IsGenericType(interfaceType) || type.GetTypeInfo().ImplementedInterfaces.Any(@interface => @interface.IsGenericType(interfaceType));
		}

		private static bool IsGenericType(this Type type, Type genericType) => type.GetTypeInfo().IsGenericType && type.GetGenericTypeDefinition() == genericType;
	}

```

and into my `startup.cs` I've this:

```csharp
public IServiceProvider ConfigureServices(IServiceCollection services)
{
   services.AddAutomapper();
   // more services ......
}
public void Configure(IApplicationBuilder app)
{
    app.UseAutoMapper();
    // more things
}
```

So, in another way it works.
The main differences between my approach and your is that I've two steps instead of one (registration + configuration) and in my mapper initialization I've added `cfg.ConstructServicesUsing(app.ApplicationServices.GetService);`

Hope it helps

**Comment by lbargaoanu** [comment]
It doesn't make sense to use the package _and_ do it by hand. You should choose one and make it work. If you find that difficult, ask a question on SO.

**Comment by lbargaoanu** [comment]
@jbogard Maybe add a few examples in ContosoUniversity (resolvers and type converters) and link to that from the home page of the package?

**Comment by imperugo** [comment]
@lbargaoanu thanks for the lesson "It doesn't make sense to use the package and do it by hand. You should choose one and make it work".
I'm pretty sure I know that, in fact the intent of my code (and I think is clear) is to share more information as possible to find the reason of the problem (if you care of course).

You already wrote me to ask to SO, I'm still writing here just because the you asked.

**Comment by imperugo** [comment]
@lbargaoanu why do you deleted my comment?

What's wrong with what I wrote?

**Comment by lbargaoanu** [comment]
There is nothing wrong with it, but this is not the right forum to have this conversation. Problems with your own code are best resolved on SO. This is a forum for problems with the package itself.

**Comment by imperugo** [comment]
My comment was about the issue related here.

If you write "**Problems with your own code are best resolved on SO**", probably you didn't read well what I wrote. 
The code posted on the first message is your code, took from the test app included in this repo.
The second block of the code is a possible solution. Good? Maybe yes maybe not but it works and this explains that there could be a solution.

I shared it here trying to help you to find the reason of the problem, but it seems you care more about your score on SO that to understand the possible problem.

**Comment by jbogard** [comment]
@lbargaoanu yeah let's open another issue. I have no idea what the original issue was. The workaround makes zero sense to me.

@imperugo If you want to use DI inside your mappings, you *must* use the instance-based version. Otherwise, how would AutoMapper know how to construct anything? It doesn't use service location to find an ambient container. Instead you use the container to build an `IMapper`, then that instance has the service factory.

**Comment by jbogard** [comment]
Also @imperugo if you open a SO question, please link to it from here. We try to reserve issues for bugs, and if it's just a usage question, that's better for SO.
