### ISSUE TITLE
Request feature: adding AssertConfigurationIsValid(); to the automapper  extension

### ISSUE THREAD

**Issue by ericvb** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#5]
Adding a possibility to do a AssertConfigurationIsValid(); when automapper is initialized via the services in the startup file.

**Comment by ericvb** [comment]
We can add Mapper.AssertConfigurationIsValid(); directly in the startup.cs file, after adding the automapper service.
I close the request.

**Comment by jbogard** [comment]
I debated putting this in, or making it configurable. But since you can just call Mapper.AssertConfigurationIsValid immediately afterward...that seemed easiest.
