### ISSUE TITLE
Object instances created with default values when combining AddAutoMapper, AddDataReaderMapping, and Profiles

### ISSUE THREAD

**Issue by artfulmethod** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#50]
When combining `AddAutoMapper()`, `AddDataReaderMapping()`, and `Profile` classes, a destination object instance's properties are populated with type default values and not with source object values.

(Hopefully this is the right repo for this issue. I wasn't sure if this one or AutoMapper.Data was appropriate.)

### Source
`IDataRecord` shape is similar to
```sql
@FirstName NVARCHAR(50),
@LastName NVARCHAR(50),
@UserId INT
```

#### User.cs
```c#
public class User
{
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public int UserId { get; set; }
}
```

### Expected
Object instance looks like
``` c#
{
    FirstName: "TestFirstName",
    LastName: "TestLastName",
    UserId: 123
}
```

### Actual
Object instance looks like
``` c#
{
    FirstName: null,
    LastName: null,
    UserId: 0
}
```

### Versions
AutoMapper.Data 1.0.1
AutoMapper.Extensions.Microsoft.DependencyInjection 3.2.0
Microsoft.AspNetCore.All 2.0.6
Microsoft.EntityFrameworkCore.SqlServer 2.0.2

### Startup.cs
``` c#
services.AddAutoMapper(config => config.AddDataReaderMapping());
```

### UserProfile.cs
``` c#
public class UserProfile : Profile
{
    public UserProfile()
    {
        this.CreateMap<IDataRecord, User>();
    }
}
```

### UserController.cs
``` c#
public class UserController : Controller
{
    private DbContext dbContext;
    private IMapper mapper;

    public UserController(DbContext dbContext, IMapper mapper)
    {
        this.dbContext = dbContext;
        this.mapper = mapper;
    }

    public async Task<IActionResult> GetAsync()
    {
        ...
        var dataReader = await command.ExecuteReaderAsync();

        await dataReader.ReadAsync();

        var user = this.mapper.Map<IDataRecord, User>((IDataRecord)dataReader);
        ...
    }
}
```

## Workarounds

Either delete UserProfile.cs and modify Startup.cs:

``` c#
services.AddAutoMapper(config => {
    config.AddDataReaderMapping();
    config.CreateMap<IDataRecord, User>();
});
```

Or be more explicit in UserProfile.cs:

``` c#
public class UserProfile : Profile
{
    public UserProfile()
    {
        this.CreateMap<IDataRecord, User>()
            .ForMember(destination => destination.FirstName, options => options.MapFrom(source => source.GetString(source.GetOrdinal("FirstName"))))
            ... etc;
    }
}
```

**Comment by lbargaoanu** [comment]
Pass an assembly or type to AddAutomapper, like [this](https://github.com/AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection).

**Comment by artfulmethod** [comment]
I get the same result.

**Comment by lbargaoanu** [comment]
Well, investigate :) Remove AutoMapper.Data for example and see how it goes.

**Comment by artfulmethod** [comment]
Without AutoMapper.Data, a fully explicit Profile class (that is, with `ForMember`, etc) is required, which makes sense. But I'd like to avoid that, if possible. :)

I've eliminated separate projects, reducing everything to just one bare bones ASP.NET Core assembly (including passing `typeof(Startup).Assembly` to `AddAutoMapper()`). No luck.

I took the same code to a new, simple .NET Core console app (with no DI). This works as expected. In the console app, no Profile class or `CreateMap` are necessary so long as `AddDataReaderMapping` is in `Mapper.Initialize`:

``` c#
Mapper.Initialize(config =>
{
    config.AddDataReaderMapping();
});
```

Back in the ASP.NET Core app, I tried removing DI and calling `Mapper.Initialize` directly in the action method. In other words, I removed AutoMapper.Extensions.Microsoft.DependencyInjection as a reference and removed anything related to AutoMapper from Startup.cs.

I'm observing the same behavior, which is an "empty" object with type default values. I am also observing some additional differences between the Web API app and the console app. The Web API app needs either a `CreateMap` or an `AddProfile` in `Mapper.Initialize` (and if the Profile class is specified, that class must have explicit `ForMember` calls) or AutoMapper will throw "AutoMapperMappingException: Missing type map configuration or unsupported mapping". The console app did not need those.

So maybe this has nothing to do with AutoMapper.Extensions.Microsoft.DependencyInjection. I'm sorry for adding this to the wrong repo.

I can definitely add `CreateMap<IDataRecord, destinationType>` calls as needed, and maybe that's what I should do.

**Comment by paultechguy** [comment]
Having the same issue.  I suspect that when calling AddProfile, the AddDataReaderMapping won't apply to that added profile.  I can remove the AddProfile (AutoMapper is supposed to scan for Profile derivations), but doing so shows that my profile class is not called.

**Were you able to solve this when using DI, AddAutoMapper, AddDataReaderMapping, and AddProfile?**

```
services.AddAutoMapper(action =>
{
	action.AddDataReaderMapping();
	action.AddProfile<MyAutoMapperProfileConfigure>();
});
```

With the above code, my custom field mappings in MyAutoMapperProfileConfigure are never  used:

```
public class AutoMapperProfileConfigure : Profile
{
	public AutoMapperProfileConfigure()
	{
		// this is never used
		CreateMap<IDataRecord, FooDto>()
			.ForMember(dest => dest.xyz, opt => opt.MapFrom(src => (string)src["field1"]))
                 ...

```

**Comment by artfulmethod** [comment]
My code has been stable with the previously mentioned workarounds, but after @paultechguy's comment I revisited this using AutoMapper.Data 2.0.0 and AutoMapper.Extensions.Microsoft.DependencyInjection 5.0.1.

I'm currently able to make everything work both with and without `AddProfile()`. Also, it works both with and without a `Profile` class (if there is no `Profile` class or no `CreateMap()`s in `services.AddAutoMapper()`, then the `IDataRecord` field names must match the destination type field names exactly).

### Startup.cs
```C#
services.AddAutoMapper(config => config.AddDataReaderMapping());
```

### Profile class
```C#
public class UserProfile : Profile
{
    public UserProfile()
    {
        this.CreateMap<IDataRecord, User>()
            .ForMember(destination => destination.FirstName, options => options.MapFrom(source => source.GetString(source.GetOrdinal("FirstNameFoobar"))))
            // etc...
    }
}
```

### Controller
```C#
var user = this.mapper.Map<IDataRecord, User>((IDataRecord)dataReader);
```

**Comment by paultechguy** [comment]
Thanks for the update.

I am able to get it to work, but my CreateMap in the Profile ctor class must explicitly set each and every field I want.  If I don't want a field, I must set it to Ignore().  If I don't do this, I won't get all the data, even if a DataReader field has the same name as my DTO member.  If I don't use Ignore() on unwanted fields, it will work, but calling myMapper.AssertConfigurationIsValid() will raise an exception.

Again, it works as long as I explicitly set every field I need or don't need (Ignore()) in my CreateMap.  The downside is that I still have to set DTO members that have the same name as a DataReader column.  Maybe that was a design decision with IDataReader support.
