### ISSUE TITLE
how to config IMapper inject Singleton

### ISSUE THREAD

**Issue by djl394922860** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#51]
I see the source code below：
`return services.AddScoped<IMapper>(sp => new Mapper(sp.GetRequiredService<IConfigurationProvider>(), sp.GetService));`
but i want to use singleton ?

**Comment by lbargaoanu** [comment]
Duplicate of #41.

**Comment by djl394922860** [comment]
got it , thank you for your reply !
