### ISSUE TITLE
Problems targeting to net461

### ISSUE THREAD

**Issue by aalmik** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#52]
Targeting console application to net461 throws Could not load file or assembly error. 
I have tried to install following NuGet packages:

AutoMapper.Extensions.Microsoft.DependencyInjection
AutoMapper
Microsoft.Extensions.DependencyInjection

`
// Set DI
            var serviceCollection = new ServiceCollection();
            ConfigureService(serviceCollection);
            var serviceProvider = serviceCollection.BuildServiceProvider();

 private static void ConfigureService(IServiceCollection serviceCollection)
        {           
            serviceCollection.AddTransient<IApplicationBusiness, ApplicationBusiness>();     
`

**Comment by lbargaoanu** [comment]
It works for me so most likely the problem is on your end.
