### ISSUE TITLE
Should TypeScan use `Assembly.DefinedTypes` instead of `ExportedTypes` ?

### ISSUE THREAD

**Issue by John0King** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#54]
https://github.com/AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection/blob/b90a1e4b1aa4ffb0cee25ca11866e6bc8a825426/src/AutoMapper.Extensions.Microsoft.DependencyInjection/ServiceCollectionExtensions.cs#L71-L74

I think this may be the reason that cause the `System.Reflection.ReflectionTypeLoadException` in  xunit test project.

**Comment by jbogard** [comment]
`ExportedTypes` is only public types, instead of all the types defined (internal, private, etc.). I think the exception you're seeing is something else.

**Comment by jbogard** [comment]
Test projects are a bit weird in how they load AppDomains and the like. In hindsight, I never should have included the ability to scan an AppDomain, because of the problems you just hit!
