### ISSUE TITLE
AddAutoMapper and WebApplicationFactory do not play nice.

### ISSUE THREAD

**Issue by VictorioBerra** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#55]
[Sample app.](https://github.com/VictorioBerra/AutoMapper.XUnit.MapperAlreadyInitialized)

I tried to use the absolute bare minimum code from basically `dotnet new mvc && dotnet new xunit` where I `AddAutoMapper` and I also have two tests class using a pretty much empty `WebApplicationFactory`. I also tossed a single profile in the mvc app. This was incredibly easy to reproduce.

`Mapper.Reset();` in my startup did not help, as well as disabling `UseStaticRegistration`. 

If I just use a single `WebApplicationFactory` then my tests do not fail so is this some weird thread issue with `IClassFixture`? From my research there should not be two separate instances of a fixture created in xunit but this could be wrong. Somehow, my startup is being initialized multiple times.

Any help is appreciated. I feel like this is an important issue because the official Microsoft tutorial and example shows how to write tests using the new WebApplicationFactory as shown [here](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.1) and anyone with two XUnit test classes inheriting from their implementation of the factory will run into this very error and their tests will fail. For what its worth, I am not running my tests in parallel.

ref https://github.com/AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection/pull/26#issuecomment-404074972

**Comment by VictorioBerra** [comment]
When I use `AutoMapper.ServiceCollectionExtensions.UseStaticRegistration = false;` the error goes away however many of my unit tests fail when something like ProjectTo attempts to run.

**Comment by VictorioBerra** [comment]
Also the most important thing here to understand is XUnit is running the test collections in parallel. It does this **by default**. The easiest and fastest way to fix this is to apply `[Collection("Sequential")]` above your test classes. This essentially gives all your classes the same collection name and xunit will run them sequentially.

This seems cleaner than the crazy mutex stuff, which if the mutex locks the thread are you really even befitting from the multi-threaded parallel code anyway? 

Ideally, I still think all of this is insane and there should be a way to register auto mapper in such a way that it does not explode.

**Comment by jbogard** [comment]
@VictorioBerra for ProjectTo, you need to pass in a configuration object (`IConfigurationProvider`) into the ProjectTo method. That can be injected in.

**Comment by VictorioBerra** [comment]
@jbogard Can i get the configuration object currently registered? Or do I need to AddSingle/Scoped my own?

**Comment by jbogard** [comment]
No, you don't. When you call `AddAutoMapper`, it registers the configuration and the mapper. So you'll just need to use the overload of `ProjectTo` that you pass in the configuration provider.

**Comment by VictorioBerra** [comment]
In the end, this appears to have worked for me. To anyone using Core, XUnit, AutoMapper, and WebAppFactory.

Set this in your startup `AutoMapper.ServiceCollectionExtensions.UseStaticRegistration = false;` and for your `ProjectTo()` statements, inject `IConfigurationProvider` and pass that instance to `ProjectTo()`. 

Using this approach, you should be able to run test in parallel without the need for Resets, Mutex, etc.

**Comment by jg11jg** [comment]
I was getting same issue around WebApplicationFactory and AddAutoMapper not working well together. (Getting lots of errors like:
```
System.Reflection.ReflectionTypeLoadException : Unable to load one or more of the requested types.
Could not load file or assembly 'Microsoft.Extensions.Identity.Core, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

``` 

Directly registering Profiles rather than having AutoMapper do its own discovery worked for me.  Rather than needing to remember to register profiles individually as I added them, I did it this way:

            var profileTypes = Assembly.GetExecutingAssembly().GetTypes()
                .Where(x => x.IsSubclassOf(typeof(Profile)));

            services.AddAutoMapper(x => x.AddProfiles(profileTypes), typeof(Startup));
