### ISSUE TITLE
ProjectTo exposes a previously fixed EF Core bug where incorrect data returned for queries projecting a single constant from a subquery.

### ISSUE THREAD

**Issue by VictorioBerra** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#57]
https://github.com/aspnet/EntityFrameworkCore/issues/10946

Error:

> Unhandled Exception: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at Microsoft.EntityFrameworkCore.Query.Expressions.SelectExpression.BindSubqueryProjectionIndex(Int32 projectionIndex, IQuerySource querySource)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)

## [Working code example with sqlite](https://github.com/VictorioBerra/ProjectTo-EFCore-IndexOutBounds)

1. clone
2. dotnet restore
3. dotnet run

The issue is caused by two thing that I can see:
- `OrderBy` + `ThenBy` using the same column.
- `ProjectTo` using a class that creates a join. IE including a nav property.

Im pretty perplexed by this, the EF core issue above was supposed to have been fixed. I think the projection is somehow bringing it back to life.

### DebugView

```csharp
.Call System.Linq.Queryable.Select(
    .Call System.Linq.Queryable.ThenBy(
        .Call System.Linq.Queryable.OrderBy(
            .Constant<Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[EFCore.Models.Cat]>(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[EFCore.Models.Cat]),
            '(.Lambda #Lambda1<System.Func`2[EFCore.Models.Cat,System.Int32]>)),
        '(.Lambda #Lambda2<System.Func`2[EFCore.Models.Cat,System.Int32]>)),
    '(.Lambda #Lambda3<System.Func`2[EFCore.Models.Cat,EFCore.Models.CatViewModel]>))

.Lambda #Lambda1<System.Func`2[EFCore.Models.Cat,System.Int32]>(EFCore.Models.Cat $x) {
    $x.MeowLoudness
}

.Lambda #Lambda2<System.Func`2[EFCore.Models.Cat,System.Int32]>(EFCore.Models.Cat $x) {
    $x.MeowLoudness
}

.Lambda #Lambda3<System.Func`2[EFCore.Models.Cat,EFCore.Models.CatViewModel]>(EFCore.Models.Cat $dtoCat) {
    .New EFCore.Models.CatViewModel(){
        Breed = .If ($dtoCat.Breed == null) {
            null
        } .Else {
            .New EFCore.Models.CatBreedViewModel(){
                BreedName = ($dtoCat.Breed).BreedName,
                Cats = .Call System.Linq.Enumerable.ToList(.Call System.Linq.Enumerable.Select(
                        ($dtoCat.Breed).Cats,
                        .Lambda #Lambda4<System.Func`2[EFCore.Models.Cat,EFCore.Models.CatViewModel]>)),
                Id = ($dtoCat.Breed).Id
            }
        },
        Id = $dtoCat.Id,
        MeowLoudness = $dtoCat.MeowLoudness,
        Name = $dtoCat.Name,
        TailLength = $dtoCat.TailLength
    }
}

.Lambda #Lambda4<System.Func`2[EFCore.Models.Cat,EFCore.Models.CatViewModel]>(EFCore.Models.Cat $dtoCat) {
    .New EFCore.Models.CatViewModel(){
        Id = $dtoCat.Id,
        MeowLoudness = $dtoCat.MeowLoudness,
        Name = $dtoCat.Name,
        TailLength = $dtoCat.TailLength
    }
}
```

**Comment by jbogard** [comment]
Try writing your query without AutoMapper. There's also an option to turn off null propagation for query mapping (`EnableNullPropagationForQueryMapping`) that removes the "if null" part, that might fix things.

**Comment by VictorioBerra** [comment]
I will try that. I like projectto because it makes writing it generic
method that can perform a projection much easier.

**Comment by jbogard** [comment]
Sure, but to debug ProjectTo, you want to first write the projection
manually with Select. Then we check the difference between that expression
and what AutoMapper builds. Manually first, verify that EF Core can even
support that query, and then compare to AutoMapper.

**Comment by VictorioBerra** [comment]
You were right, I was able to repro with a manual projection like so:

```csharp
var results = context.Cat
    .OrderBy(x => x.MeowLoudness)
    .ThenBy(x => x.MeowLoudness)

    .Select(x => new CatViewModel()
    {
        Id = x.Id,
        Name = x.Name,
        Breed = new CatBreedViewModel() {
            Id = x.Breed.Id,
            BreedName = x.Breed.BreedName,
            // Comment below line to fix bug.
            Cats = x.Breed.Cats.Select(y => new CatViewModel()
            {
                Id = y.Id,
                MeowLoudness = y.MeowLoudness,
                Name = y.Name,
                TailLength = y.TailLength
            }).ToList()
        },
        MeowLoudness = x.MeowLoudness,
        TailLength = x.TailLength
    })
    .ToList();
```

The issue here is the inner projection. I will get this over to the EF Core team.
