### ISSUE TITLE
Initialization doesn't work

### ISSUE THREAD

**Issue by lindeberg** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#59]
When automapper-calling code like ProjectTo<>() is called I receive:
````
An unhandled exception occurred while processing the request.
InvalidOperationException: Mapper not initialized. Call Initialize with appropriate configuration. If you are trying to use mapper instances through a container or otherwise, make sure you do not have any calls to the static Mapper.Map methods, and if you're using ProjectTo or UseAsDataSource extension methods, make sure you pass in the appropriate IConfigurationProvider instance.
````

This code used to work before updating a bunch of nugets to the latest versions.

In startup I'm using
 ```services.AddAutoMapper(typeof(Startup));```

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#mappermap-usage

**Comment by lindeberg** [comment]
Thanks! Oh wow, not so clean but I guess it makes sense with dependency injection.
