### ISSUE TITLE
AspNetCore Dependency

### ISSUE THREAD

**Issue by ChristopherHaws** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#60]
Hi Jimmy,

It looks like in v5 of this library you have taken on an AspNetCore dependency, but we use this in an MVC5 apps, console apps, as well as AspNetCore apps. It looks like the reason for the dependency is the `ConfigurationAssertMiddleware`. Do you think it makes sense for this to be in a separate package? It seems weird to me to have `AutoMapper.Extensions.Microsoft.DependencyInjection` depend on an AspNetCore package.

Thanks! :)

**Comment by jbogard** [comment]
This is now released! Thanks for the heads up. WHOOPS
