### ISSUE TITLE
[5.0.1] Doesn't register user-defined profiles

### ISSUE THREAD

**Issue by Deilan** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#62]
As of `5.0.1` `services.AddAutoMapper();` doesn't register user-defined mapping `Profile`s from the executing assembly. Immediate subsequent call of `Mapper.AssertConfigurationIsValid();` throws an `InvalidOperationException`:

![image](https://user-images.githubusercontent.com/4777512/43048764-8592622c-8df5-11e8-9003-ce1d24062d64.png)

But `4.0.1` works just fine.

Env: ASP.NET Core 2.1.

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#mappermap-usage

**Comment by Deilan** [comment]
@lbargaoanu As of this writing the readme section you are reffering to doesn't relates to an initialization, it explains the runtime nuances. Elaborate please.

**Comment by jbogard** [comment]
It says you cannot use the static part anymore. Anywhere.
