### ISSUE TITLE
exception resolving IMapper in tests

### ISSUE THREAD

**Issue by af4jm** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#65]
In integration tests (with MSTest & TestServer), all tests throw InvalidOperationException "Cannot resolve scoped service 'AutoMapper.IMapper' from root provider".  Changing the `IMapper` registration from Scoped to Transient allows the tests to pass.

Running AutoMapper 6.2.1 because of https://github.com/AutoMapper/AutoMapper.Data/issues/30

Test results including error message...

> Test Name:	OnGet_NoFound
> Test FullName:	MyCompany.MyApp.Test.RazorPages.EmployeeInfoPageTest.OnGet_NoFound
> Test Source:	C:\src\MyApp\MyCompany.MyApp.Test\RazorPages\EmployeeInfoPageTest.cs : line 70
> Test Outcome:	Failed
> Test Duration:	0:00:00.1919067
> 
> Result StackTrace:	
> at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.ValidateResolution(Type serviceType, IServiceScope scope, IServiceScope rootScope)
>    at Microsoft.Extensions.DependencyInjection.ServiceProvider.Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceProviderEngineCallback.OnResolve(Type serviceType, IServiceScope scope)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
>    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
>    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
>    at MyCompany.MyApp.Test.RazorPages.EmployeeInfoPageTest.TestInit() in C:\src\MyApp\MyCompany.MyApp.Test\RazorPages\EmployeeInfoPageTest.cs:line 35
> Result Message:	Initialization method MyCompany.MyApp.Test.Unit.RazorPages.EmployeeInfoPageTest.TestInit threw exception. System.InvalidOperationException: Cannot resolve scoped service 'AutoMapper.IMapper' from root provider..
> Result StandardOutput:	
> info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
>       User profile is available. Using 'C:\Users\jmeyer\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.

Test startup class is as follows...

```csharp
namespace MyCompany.MyApp.Test
{
    using System;
    using System.IO;
    using System.Linq;
    using System.Reflection;
    using Microsoft.AspNetCore;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.TestHost;
    using Microsoft.Extensions.Configuration;
    using Microsoft.Extensions.DependencyInjection;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using MyCompany.MyApp.Core.Repositories;
    using MyCompany.MyApp.Test.RepositoryMocks;

    [type: TestClass]
    public class TestsStartup
    {
        public static TestServer TestServer { get; private set; }

        public static IConfiguration Configuration { get; private set; }

        public static IServiceProvider ServiceProvider => TestServer.Host.Services;

        [method: AssemblyInitialize]
        public static void InitializeContext(TestContext testContext)
        {
            if (testContext.Properties.TryGetValue("ASPNETCORE_ENVIRONMENT", out var environment))
            {
                Environment.SetEnvironmentVariable("ASPNETCORE_ENVIRONMENT", (string)environment, EnvironmentVariableTarget.Process);
            }

            string environmentName = Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT", EnvironmentVariableTarget.Process) ?? EnvironmentName.Production;

            Configuration = new ConfigurationBuilder()
                .SetBasePath(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location))
                .AddJsonFile("appsettings.json", optional: true)
                .AddJsonFile($"appsettings.{environmentName}.json", optional: true)
                .AddEnvironmentVariables()
                .Build();

            TestServer = new TestServer(WebHost.CreateDefaultBuilder<Web.Startup>(Array.Empty<string>())
                .UseEnvironment(environmentName)
                .UseConfiguration(Configuration)
                .ConfigureTestServices(ConfigureTestServices));
        }

        public static void ConfigureTestServices(IServiceCollection serviceCollection)
        {
            serviceCollection.Remove(serviceCollection.First(sd => sd.ServiceType == typeof(IEmployeeRepository) && sd.Lifetime == ServiceLifetime.Transient));
            serviceCollection.AddTransient<IEmployeeRepository, EmployeeRepositoryMock>();
        }
    }
}
```

**Comment by jbogard** [comment]
`IMapper` *needs* to be scoped, not transient. Your tests use a global service provider, which isn't quite correct. All requests execute in a scope, so you really need to be creating a scope before performing any action against the container.

Note - you'll hit this with other dependencies too, like EF Core's `DbContext`.

What I do in integration tests is to [wrap any action in a scope](https://github.com/jbogard/ContosoUniversityDotNetCore-Pages/blob/master/ContosoUniversity.IntegrationTests/SliceFixture.cs#L40), so that I'm always working with a service scope instead of with the root service provider. My apps *never* deal with the root service provider, they're always inside a scope, so I replicate that behavior in my tests.
