### ISSUE TITLE
Remove AddAutoMapper without parameters

### ISSUE THREAD

**Issue by lbargaoanu** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#68]
People struggle with this constantly.

**Comment by lbargaoanu** [comment]
Marking it as deprecated would have the advantage of an useful error message, but I don't know...

**Comment by jbogard-hs** [comment]
What would it look like to have something like:

```c#
IServiceCollection AddAutoMapper(Type assemblyTypeToSearch);
IServiceCollection AddAutoMapper(params Type[] assemblyTypesToSearch);
```

Would that make it more obvious? I don't know how we get away from the `params` version.

**Comment by lbargaoanu** [comment]
I would have only the params version. But if you're saying that you want it to be obvious that you can pass only one instance, I guess I understand :)
