### ISSUE TITLE
Service.AddAutoMapper() breaks when using v5.0.1

### ISSUE THREAD

**Issue by dylanwind** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#69]
Please check comments in 
https://app.pluralsight.com/library/courses/building-async-api-aspdotnet-core/discussion
this function broken in v5.0.1 and works in v4.0.1

**Comment by dylanwind** [comment]
Using v4.0.1, add this in ConfigureServices, works
            Service.AddAutoMapper()

Using v5.0.1, add this in ConfigureServices, get error "Mapper not initialized"
            Service.AddAutoMapper()
must add explicit initialization to make it work:
            services.AddAutoMapper();
            Mapper.Initialize(cfg => cfg.AddProfile<profilename>());

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#mappermap-usage

**Comment by dylanwind** [comment]
Thanks for the link. 
It seems the static Map function is not recommended in v5.0.1 now.

Could you please give me an idea how to use _mapper.Map in a custom ResultFilterAttribute?

https://github.com/KevinDockx/BuildingAsyncAPIAspNetCore/blob/master/Finished%20sample/Books/Books.Api/Filters/BookResultFilterAttribute.cs

**Comment by lbargaoanu** [comment]
I would change the question to how do you do DI  in general in a custom ResultFilterAttribute. I don't have an answer to that, but surely it's possible somehow.

**Comment by jbogard** [comment]
With any filter, they don't want you to do constructor injection. Filters typically have a singleton lifecycle. Instead, core ASP.NET extensions pass in a `context` parameter that then gives you access to an `IServiceProvider`. So that example should be:

```c#
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Books.Api.Filters
{
    public class BookResultFilterAttribute : ResultFilterAttribute
    {
        public override async Task OnResultExecutionAsync(ResultExecutingContext context, 
            ResultExecutionDelegate next)
        {
            var resultFromAction = context.Result as ObjectResult;
            if (resultFromAction?.Value == null
               || resultFromAction.StatusCode < 200
               || resultFromAction.StatusCode >= 300)
            {
                await next();
                return;
            }
            
            var mapper = context.HttpContext.RequestServices.GetService<IMapper>();
            resultFromAction.Value = mapper.Map<Models.Book>(resultFromAction.Value);

            await next();
        }
    }
}
```

**Comment by jbogard** [comment]
FYI that `GetService<T>()` method is an extension method in the `Microsoft.Extensions.DependencyInjection` namespace.

**Comment by dylanwind** [comment]
You're right! 💯
