### ISSUE TITLE
Cannot get it to work from Unit Test project - xUnit

### ISSUE THREAD

**Issue by lisamariet** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#71]
Cannot really pinpoint what is wrong.. 
This is when using the same setupcode as project I am testing. And the Windowsservice runs fine with this code:
`
services.AddAutoMapper(x => x.AddProfile<MyProfileClassFromAnotherProject>());
`

but the xUnit test fails with this exception:

> System.AggregateException : One or more errors occurred. (Unable to load one or more of the requested types.
Could not load type 'System.ServiceProcess.ServiceAccount' from assembly 'System.ServiceProcess, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
Could not load file or assembly 'System.Configuration.Install, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.ServiceProcess.ServiceController, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load type 'System.ServiceProcess.ServiceAccount' from assembly 'System.ServiceProcess, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.) (The following constructor parameters did not have matching fixture data: AniNotificationWorkerTestScenarioContext context)
---- System.Reflection.ReflectionTypeLoadException : Unable to load one or more of the requested types.
Could not load type 'System.ServiceProcess.ServiceAccount' from assembly 'System.ServiceProcess, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
Could not load file or assembly 'System.Configuration.Install, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.ServiceProcess.ServiceController, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load type 'System.ServiceProcess.ServiceAccount' from assembly 'System.ServiceProcess, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
---- The following constructor parameters did not have matching fixture data: AniNotificationWorkerTestScenarioContext context

----- Inner Stack Trace #1 (System.Reflection.ReflectionTypeLoadException) -----
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at AutoMapper.ServiceCollectionExtensions.AddAutoMapperClasses(IServiceCollection services, Action`1 additionalInitAction, IEnumerable`1 assembliesToScan) in C:\projects\automapper-extensions-microsoft-dependencyinjectio\src\AutoMapper.Extensions.Microsoft.DependencyInjection\ServiceCollectionExtensions.cs:line 69

I am not sure why it is trying to load these system services? Nor why the same code does not fail when running the windows service. (BTW windows service project is a .net 461 whilst the Test project is .net core 2.0)

![image](https://user-images.githubusercontent.com/5948299/45954890-9b288800-c00e-11e8-8644-11a4e4a5990a.png)

**Comment by lbargaoanu** [comment]
That's just an assembly scanning error, it has little to do with AM. You should pass explicitly the assemblies to scan.

**Comment by lisamariet** [comment]
Yes I tried that.. but then the production code does not work ones deployed on a server as a windows service and running as that user. It seems to be looking for the assembly not in project bin folder, but in System/bin/debug folder. So only way I can get it to work, is to use the above method in production code and replace in xunit test project with specific assembly.. but then I am not really testing the production code ...

**Comment by lbargaoanu** [comment]
If you explicitly pass the assemblies to AM, obviously AM won't be looking for any assemblies. So the gist of your issue is app specific.

**Comment by jbogard** [comment]
I hit this sometimes, and basically I just need to add those references.

The gist is for running in the full .NET framework, the runtime can look in the GAC for assembly probing. Those assemblies you highlight there are installed in the GAC with full .NET.

There is no GAC for .NET Core, so those tests can't look in the GAC for missing assembly references. For .NET Core, you need to explicitly add those package references.

One suggestion I have though - be careful with running tests in a different target framework than what you're deploying. Full .NET and .NET Core do have subtle differences (like you're seeing here).

It gets more complicated than this - technically if you want to run some library both on full .NET and .NET Core, it should target some variant of `netstandard`, most likely `netstandard2.0`. You'd have:

```
CoreLibrary (netstandard20)
TestLibrary (netcoreapp2.1) -> CoreLibrary
Service (net461) -> CoreLibrary
```

If you did this, you'd see compile errors for missing package references in your core library, forcing you to add them.
