### ISSUE TITLE
Add strong name

### ISSUE THREAD

**Issue by pbeny** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#75]
Please sign assembly with strong name.

**Comment by lbargaoanu** [comment]
Most likely that's not going to happen. But see [this](https://github.com/brutaldev/StrongNameSigner).

**Comment by jbogard** [comment]
https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/strong-naming#create-strong-named-net-libraries

Looks like the guidance has changed

**Comment by lbargaoanu** [comment]
Yes, I saw that, but I would guess most people still hate strong names :)

**Comment by lbargaoanu** [comment]
Maybe add a strong name only on .Net Core?

**Comment by pbeny** [comment]
Thank you, it was helpful.

**Comment by lbargaoanu** [comment]
Fixed by #76.
