### ISSUE TITLE
Using TestServer causing exception to throw during AddAutomapper for concurrently executing test suites

### ISSUE THREAD

**Issue by ts46235** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#82]
When running multiple integration test suites that use `TestServer` to test web api endpoints I am getting the below exception. Each test suite has their own Startup class that calls `AddAutoMapper`. Each test/suite is run in parallel. The problem only happens when more than one suite is run together (I have 5 suites and two always fail one test  when all 5 run and if I remove the failed test, another one in that project or a different project will start failing).

Stepping thru the code I see that multiple threads are inside of `AddAutoMapperClasses` at the same time and are past the check that is at the start of the method```if (services.Any(sd => sd.ServiceType == typeof(IMapper)))
                return services;``` so it seems that check is not enough to step multiple current thread execution

I think this line is cause of exception to be originally thrown
`.SelectMany(a => a.DefinedTypes)`
```Unable to load one or more of the requested types.
Could not load type 'Castle.Proxies.ISetup`2Proxy' from assembly 'DynamicProxyGenAssembly2, Version=0.0.0.0, Culture=neutral, PublicKeyToken=a621a9e7e5c32e69'.

   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
```
Later on I get a more complete exception but its most likely caused by/same as above::
```System.Reflection.ReflectionTypeLoadException: 'Unable to load one or more of the requested types.
Could not load type 'Castle.Proxies.ISetup`2Proxy' from assembly 'DynamicProxyGenAssembly2, Version=0.0.0.0, Culture=neutral, PublicKeyToken=a621a9e7e5c32e69'.
Could not load type 'Castle.Proxies.Invocations.IReturns`2_Returns' from assembly 'DynamicProxyGenAssembly2, Version=0.0.0.0, Culture=neutral, PublicKeyToken=a621a9e7e5c32e69'.'

   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at AutoMapper.ServiceCollectionExtensions.AddAutoMapperClasses(IServiceCollection services, Action`2 configAction, IEnumerable`1 assembliesToScan) in C:\projects\automapper-extensions-microsoft-dependencyinjectio\src\AutoMapper.Extensions.Microsoft.DependencyInjection\ServiceCollectionExtensions.cs:line 72
   at Test.Startup.ConfigureServices(IServiceCollection services) in C:\app\Testing\src\Test.Api\Startup.cs:line 90
--- End of stack trace from previous location where exception was thrown ---
   at   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

Similar to 
#37 
and Similar to the resolution from 
#36
, The only fix we've found is to wrap in try/catch:

```
private static Mutex mutex = new Mutex();
public void ConfigureServices(IServiceCollection services)
        {
            mutex.WaitOne();
            Mapper.Reset();

            try
            {
                services.AddAutoMapper();
            }
            catch (Exception)
            {
                Thread.Sleep(2000);
                services.AddAutoMapper();
            }

            mutex.ReleaseMutex();
```

Thanks!

**Comment by lbargaoanu** [comment]
You can explicitly pass the assemblies to AddAutoMapper. Or make a PR that excludes dynamic assemblies from the scanned list.

**Comment by ts46235** [comment]
so what are you saying the underlying problem is?

**Comment by lbargaoanu** [comment]
The problem is that you're telling AM to scan all assemblies and some are dynamic.
