### ISSUE TITLE
Duplicate profiles inside IMapperConfigurationExpression

### ISSUE THREAD

**Issue by sungam3r** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#85]
Imagine a situation where a client code accidentally makes a call, passing the same type or assembly into this method:
 ```c#
services.AddAutoMapper(typeof(Source), typeof(Source), typeof(Source));
```
This may be due to the fact that it calculates a list of marker types (or assemblies) according to some logic at runtime, not compile-time.

So eventually this will result in [this line](https://github.com/AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection/blob/master/src/AutoMapper.Extensions.Microsoft.DependencyInjection/ServiceCollectionExtensions.cs#L88) being executed several times for the same type. The same profile will be registered several times inside `MapperConfigurationExpression`. The same applies to other objects - they will be registered in `IServiceCollection` collection several times which may have induced errors when resolving components from the container. When checking the configuration with `AssertConfigurationIsValid` method we will get `AutoMapper.DuplicateTypeMapConfigurationException`:
```c#
// modified test from AutoMapper.Extensions.Microsoft.DependencyInjection.Tests.DependencyTests
public DependencyTests()
{
    IServiceCollection services = new ServiceCollection();
    services.AddTransient<ISomeService>(sp => new FooService(5));
    services.AddAutoMapper(typeof(Source), typeof(Source), typeof(Profile));
    _provider = services.BuildServiceProvider();
    var p = _provider.GetService<IConfigurationProvider>();
    p.AssertConfigurationIsValid(); // OOPS! DuplicateTypeMapConfigurationException here
}
```

It seems to me that:
1) `AddAutoMapperClasses` method should take into account the possibility of passing in the parameters of the same assemblies ([this line](https://github.com/AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection/blob/master/src/AutoMapper.Extensions.Microsoft.DependencyInjection/ServiceCollectionExtensions.cs#L67) is not enough here).
2) It is probably better to explicitly throw an exception when trying to call the `AddAutoMapperClasses` method again instead of just returning silently. A repeated call can come with a completely different set of parameters from a completely different module (package) and the first module will win, and for the second module its profiles will be silently ignored.
3) It would be great if the `IMapperConfigurationExpression.AddProfile(Type profileType)` method itself became idempotent and stopped adding the same type several times. The same wish also applies to other methods inside `IMapperConfigurationExpression` that accept assemblies or types as input.

**Comment by lbargaoanu** [comment]
On the other hand, you can do that in your own code :)

**Comment by lbargaoanu** [comment]
Or you can try a PR. Probably a distinct for assemblies would do it.

**Comment by sungam3r** [comment]
In my code I can do a lot of useful things, this is not about that. The point is that once a library has been created to resolve the issue of integration with Microsoft.DependencyInjection, then it should do it as correctly as possible, eliminating the need for customers to write unnecessary repeating code.

**Comment by lbargaoanu** [comment]
As I've said, a PR is welcome.
