### ISSUE TITLE
AddAutoMapperProxy proposal

### ISSUE THREAD

**Issue by sungam3r** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#88]
The `AddAutoMapper` method allows you to register an `IMapper` instance and auxiliary entities in a `IServiceCollection` container. Next, you can inject the `IMapper` dependency inside the application.
This is suitable in most cases if full compliance with the principle of dependency inversion is not required. However, in large applications that have a layered architecture, this can lead to negative
consequences, since the introduction of dependency on the `IMapper` violates one of DI principles:

> Abstractions should not depend on details. Details should depend on abstractions.

In this case, the `IMapper` interface acts as an implementation, not an abstraction, since the code using it makes a dependency on a specific library (and version) that implements the function of mapping objects.
To avoid this, the developer can define his own dependency interface and accept it into the constructor instead of the `IMapper` interface:
```c#
public interface IConverter
{
    TDestination Convert<TDestination>(object source);
}

public class EmployeesController {
	private readonly IConverter _converter;

	public EmployeesController(IConverter converter) // no more direct dependency from AutoMapper package
		=> _converter = converter;

	// use _converter.Convert
}
```

And register proxy in composition root:
```c#
services.AddAutoMapperProxy<IConverter>();
//or
services.AddAutoMapperProxy(typeof(IConverter));
```

In this case, the application libraries do not contain an external dependency on the AutoMapper package. The only place that sets the dependency is the composition root. If necessary, the specific
implementation of the mapping mechanism can be easily changed without the need to edit the code of the entire application.

Under the hood, the `AddAutoMapperProxy` method builds a special proxy class in runtime and adds scoped dependency from it into `IServiceCollection`. Methods of this class just delegate calls
to `IMapper`. Matching is done by the methods signature, the name of method can be arbitrary. It should be noted that exactly the same class could be created by the developer at compile time to
solve the above problem. In this regard, the `AddAutoMapperProxy` method frees the developer from this boring job.

Supported proxied `IMapper`'s methods:
```c#
TDestination Map<TDestination>(object source);
TDestination Map<TSource, TDestination>(TSource source);
TDestination Map<TSource, TDestination>(TSource source, TDestination destination);
object Map(object source, Type sourceType, Type destinationType);
object Map(object source, object destination, Type sourceType, Type destinationType);
```

**Comment by jbogard** [comment]
The DIP does not mean “abstract everything”. It also does not mean “do not use libraries directly”. If you abstract IMapper, it means you won’t be able to use some of its overloads that are quite specific.

I recommend against these kinds of abstractions, whether AutoMapper, EF, logging etc. and I don’t want to support this in my library.

You can still do it yourself, however!

**Comment by sungam3r** [comment]
> The DIP does not mean “abstract everything”.

I agree. There is no point in abstracting stable dependencies - dependencies of this kind, whose nature is static or whose implementation is unlikely to ever change. Is AutoMapper stable dependency? In version 8 there were breaking changes. It's nice to see that the library develops and does not stand still. However, the regular release of new major versions has some problems for consumers. Having a stack of libraries (possible from different team members), each of which uses an AutoMapper, you cannot just take and update the AutoMapper package. There will be errors in runtime due to transitive dependencies with which libraries are compiled. You have to recompile each of the libraries for the new version to use all of them together. DIP completely eliminates this problem - just update the implementation in one place - in composition root, without touching the other parts.

> If you abstract IMapper, it means you won’t be able to use some of its overloads that are quite specific.

Of course, this is obvious, as well as the fact that these rather specific overloads are used in rather specific cases, while in 99% of cases a basic standard set of possibilities is used.

I agree that all of this can be done in a separate package (which is happening now). But since there is this package, specifically designed for integration with Microsoft.DependencyInjection, it seemed to me that it would be right to place it here.

Anyway, thanks for the feedback!

**Comment by jbogard** [comment]
Ah, so consumers wouldn't reference AutoMapper at all. The mapping API may be simple, but the configuration API is not. Each consumer should create their own `Profile`s so that they all explicitly register their own mapping configuration. I tend too to keep mapping configuration very close to the definition of the destination types - so it's very easy for developers to see the config.

**Comment by sungam3r** [comment]
>Ah, so consumers wouldn't reference AutoMapper at all.

Exactly.

>Each consumer should create their own `Profile`s so that they all explicitly register their own mapping configuration. I tend too to keep mapping configuration very close to the definition of the destination types

Let's present a simple example. There is a Web API project with a layer of models, a layer of data, a layer of business logic and a layer of controllers (web framework dependent root layer). Under the layer, I mean a separate assembly. The model layer consists of a view models that define the form of input and output contracts. The data layer works with the entities of the EF. Naturally, we need as a result of the work to somehow convert objects from the EF entities into view models.

**Where should mapping be located - data layer or model layer?**

In the first case, the data layer receives a dependence on a specific external representation, and there may be several such representations. When the second view appears, edit the data layer? In the second case, the picture is even worse - the presentation layer gets dependent on the low-level implementation layer (the view assembly gets dependency on the EF assembly).

This statement
>I tend too to keep mapping configuration very close to the definition of the destination types

also raises a question. After all, mappings are often made bidirectional. In our case, the web app will have mappings for reading data and mappings for writing data. In the first case, destination types are view models, and in the second, EF-types.

The point is that mappings **do not really belong** in this system either to the model layer or to the data layer. Mapping is the glue that binds the two layers. This is the attitude of the third party (the logic layer or even the root of the application) in relation to how it wants to link the two underlying layers to each other.

In such a layered system, the profiles can be located either in the layer of controllers or (even better) in separate assemblies, intended solely for mapping profiles. Next, the profiles from these assemblies are loaded into the DI-container by composition root code using the `AddAutoMapper` method.

I repeat that the problem described only applies to layered applications :
> This is suitable in most cases if full compliance with the principle of dependency inversion is not required. However, in large applications that have a layered architecture, this can lead to negative
consequences

In the case of monolithic applications, there is no such problem as a class.

**Comment by jbogard** [comment]
Is this all for a single application though? I don't see what all this layering actually buys you:

https://vimeo.com/131633177

Since I'm squarely in the camp of "layered architectures are generally a waste of time"...well...

**Comment by sungam3r** [comment]
> Is this all for a single application though?

Something for a specific application, something for different applications. There are quite a few reusable parts within our microservice infrastructure.

Thanks for the link. I watched the video you gave completely and examined the source code of the ContosoUniversity demo. From it it became clear that you indeed are describing a monolithic application containing all your code in one project. Moreover, it is still a fairly simple application (as it usually happens for demonstration examples) of "hello world" level. What can we say about real projects? Honestly, I find it strange to hear "layered architectures are generally a waste of time" statement. It is difficult to imagine a modern commercial project that is being conducted in this way. The overhead of managing the code base, conflicts of interests of the team members, the complexity/impossibility of independent releases, and simply the question of code reuse - after all, such a project may not be the only one, and neighboring projects will probably need to re-implement some parts. Actually, this is all - the classic problems of monoliths.

Do I understand correctly that ideologically AutoMapper is designed to be used in such monolithic applications like ContosoUniversity?
