### ISSUE TITLE
Internal Types Not Discovered

### ISSUE THREAD

**Issue by msfreed** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#9]
Internal types are not auto-discovered when using the default behavior of AddAutoMapper()

**Comment by bruno-garcia** [comment]
Isn't that the desired behavior?
In case you expect a type to be loaded/discovered, shouldn't you exposed it (i.e: _public_)?

**Comment by jbogard** [comment]
That would be the easiest way to fix it, just make your profiles public.

**Comment by msfreed** [comment]
The profiles were public, but the custom type converters were marked internal.
It wasn't obvious that the problem was that the converters were marked internal. I had to come here to the source to discover that it was only looking at public types.

**Comment by jbogard** [comment]
This is released with 1.2.0.
