### ISSUE TITLE
Remove automatic assembly scanning

### ISSUE THREAD

**Issue by jbogard** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#90]
Seems like it just causes more problems than it's worth. We can keep the params one, but maybe add overloads that take one assembly, then params and assert.

**Comment by lbargaoanu** [comment]
Yes, the assemblies should be required. People can explicitly pass LoadedAssemblies if they want that.

**Comment by lbargaoanu** [comment]
Fixed by https://github.com/AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection/commit/507b1ff19ed46104730b2c4eddfc28564cd259d3. I meant to open a PR, but I was not paying attention :)
