### ISSUE TITLE
Automapper Lifetime should be configurable during registration

### ISSUE THREAD

**Issue by ivankarpey** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#91]
One of the main dep in aspnetcore is dbcontext. It's possible to configure any lifetime for it currently so something similar should be allowed also for an automapper.

we currently build a microservice project which handles messages from a bus and 95% of our services are transient. But we can't use automapper since it's configured as scoped.

**Comment by lbargaoanu** [comment]
A PR is welcome. Of course there will be some overhead creating multiple mappers per request.
