### ISSUE TITLE
Mapping profile is only loaded after the first request

### ISSUE THREAD

**Issue by kanup** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#92]
In a do net core I have added automapper this way:
` services.AddAutoMapper(new Assembly[] { typeof(AutoMapperProfile).GetTypeInfo().Assembly` });`

I inject mapper in the service class this way:
`public XYZService(IMapper mapper){}`

I tried placing a beakpoint in my AutomapperProfile, but it is only hit after the first request is made (i.e. after the first need for IMapper dependency). I was expecting automapper to initialize mappings in the startup.

**Comment by kanup** [comment]
I realised that a work-around can be to inject IMapper to Configure method in Startup.cs:
`public void Configure(..., IMapper mapper)`

I'm not sure if this is the recommended way to go.

Please note, I do not wish to call:
` mapper.ConfigurationProvider.AssertConfigurationIsValid();`
in startup.cs because I have it in my test project, so I don't want this extra check in the startup. This means, with this work-around, I will be injecting IMapper to Configure() method as an unused dependency.

**Comment by lbargaoanu** [comment]
http://docs.automapper.org/en/latest/Configuration.html#configuration-compilation
