### ISSUE TITLE
App crash when trying to inject IMapper into IHostedService in .Net Core 2.2

### ISSUE THREAD

**Issue by ymelnychuk** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#94]
I'm not sure if this even possible or I'm just doing it all wrong, but when I try in inject IMapper into a hosted service it crashes IISExpress. I extracted it to a empty Core 2.2 Web App, with single hosted service MyTask. The only extra package installed is Microsoft.Extensions.DependencyInjection. Here is the code:

`using AutoMapper;
    using Microsoft.AspNetCore.Builder;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Http;
    using Microsoft.Extensions.DependencyInjection;

    public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddAutoMapper();

            services.AddHostedService<MyTask>();
        }

        public void Configure(IApplicationBuilder app, IHostingEnvironment env, IMapper mapper)
        {
            mapper.ConfigurationProvider.AssertConfigurationIsValid();

            app.Run(async (context) =>
            {
                await context.Response.WriteAsync("Hello World!");
            });
        }
    }`

And MyTask service class:
`   using System;
    using System.Threading;
    using System.Threading.Tasks;
    using AutoMapper;
    using Microsoft.Extensions.Hosting;
    using Microsoft.Extensions.Logging;

    public class MyTask : IHostedService, IDisposable
    {
        private readonly IMapper _mapper;
        private readonly ILogger _logger;
        private Timer _timer;

        public MyTask(
            IMapper mapper,
            ILogger<MyTask> logger)
        {
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
            _mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));
        }

        public async Task StartAsync(CancellationToken cancellationToken)
        {
            _logger.LogInformation("Task Service is starting.");

            _timer = new Timer(DoWork, null, TimeSpan.Zero, TimeSpan.FromSeconds(30));
        }

        public void DoWork(object state)
        {
            _logger.LogInformation("Task Service heartbeat.");
        }

        public Task StopAsync(CancellationToken cancellationToken)
        {
            _logger.LogInformation("Task Service is stopping.");

            _timer?.Change(Timeout.Infinite, 0);

            return Task.CompletedTask;
        }

        public void Dispose()
        {
            _timer?.Dispose();
        }
    }`

By removing IMapper here I can run this app with no issues. Any suggestion? Thanks, -Yuri

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
