### ISSUE TITLE
Allow custom ServiceLifetime of IMapper

### ISSUE THREAD

**Issue by jbogard** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#96]
See https://github.com/aspnet/EntityFrameworkCore/blob/master/src/EFCore/EntityFrameworkServiceCollectionExtensions.cs#L65

**Comment by jholovacs** [comment]
It doesn't seem like there'd be much effort involved in this?  If the IMapper doesn't maintain a state, and there's no technical constraints (as per #97), it's basically adding an optional parameter to the `.AddAutoMapper()` [extension](https://github.com/AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection/blob/e2ada978f3489fa8ba132e8a0f715de1b2288615/src/AutoMapper.Extensions.Microsoft.DependencyInjection/ServiceCollectionExtensions.cs#L18) class, and some updates to the config object?

**Comment by jbogard** [comment]
What should happen with all the extension points? Really if `IMapper` is singleton, then all of the related services would need to be, too.

**Comment by jholovacs** [comment]
I would think the ones registered as `Transient` could probably stay transient, regardless of service lifetime, it won't break anything.  `IConfigurationProvider` is already singleton.  I'll send a PR to you in a bit for you to take a look at.

**Comment by jholovacs** [comment]
PR #98 for review.
