### ISSUE TITLE
Change default lifetime of IMapper to transient?

### ISSUE THREAD

**Issue by jbogard** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#97]
More of a question. There's not really anything "scoped" about our mapper, and the configuration is already singleton.

We have two dependencies in `Mapper`:

- `IConfigurationProvider configurationProvider`
- `Func<Type, object> serviceCtor`

Our mapper isn't disposable, doesn't cache anything per mapping operation(s), and doesn't hold any state. I think we may have had a reason to scope it in the past, but I can't see any now.

**Comment by jbogard** [comment]
See also:

- #91 
- #81 
- #51 
- #41 

Singleton is a bad default of course, but transient would be the least restrictive of all options. There's no technical reason to force a scope, from what I can see.

**Comment by jholovacs** [comment]
Agreed that singleton is a bad default, and also agreed that there's no technical reason to force a scope.  This should make usage a lot more flexible.

**Comment by lbargaoanu** [comment]
The mapper does hold some state that gets reused across Map calls. For most use cases I think one mapper per request is all it's needed.

**Comment by jbogard** [comment]
What state is re-used? The only thing I can see is the `DefaultContext`.

**Comment by jbogard** [comment]
All the cached plans are in `MapperConfiguration` which is already registered singleton.

**Comment by lbargaoanu** [comment]
Yes, that one, and its child, MappingOperationOptions.

**Comment by jbogard** [comment]
I'm not sure it's worth the constraint of scoped, given that the cached objects would only be used on multiple maps per request.

**Comment by lbargaoanu** [comment]
Not exactly a constraint. It should be configurable. But the right default I believe.

**Comment by jholovacs** [comment]
If it's configurable, why not go with the most atomic as the default (which would be transient)?  I'd imagine the most popular usage of the `IMapper` would be either injecting it into a single controller or service in a single scope, so there may not be a practical difference for 90% of use cases.

**Comment by jbogard** [comment]
@jholovacs let's have the configurable discussion in #96

**Comment by jbogard** [comment]
@lbargaoanu scoped has constraints, I mean, and when we chose `Scoped` we inherited those constraints.

**Comment by lbargaoanu** [comment]
All the services are already transient. Users care only insomuch as that they cannot inject IMapper in singletons. If that's a problem, we can make it singleton. I don's see why anybody would care but us.
